from app.application.documents.text_utils import (
    clean_text_lines,
    generate_text_variants,
    is_plausible_order_number,
    normalize_identifier_token,
    normalize_line,
    normalize_multiline_text,
    normalize_text,
    parse_amount,
    parse_date_value,
    parse_decimal_value,
    score_tesseract_ocr_variant,
    score_text_quality,
    select_best_tesseract_ocr_variant,
    select_best_text_variant,
)
