import { adminTabDescriptions, techAdminTabDescriptions } from "./appUiConfig";
import {
  formatCatalogCodeLabel,
  formatCompactNumber,
  formatDateTime,
  formatDateValue,
  formatFileSize,
  formatHours,
  formatMoney,
  formatOcrFieldLabel,
  formatOcrLearningStatusLabel,
  formatOcrProfileName,
  formatOcrSignalTypeLabel,
  formatReviewBucketLabel,
  formatReviewRuleTypeLabel,
  formatSourceTypeLabel,
  formatStatus,
  formatUserRoleLabel,
  formatValueParserLabel,
  formatVehicleTypeLabel,
} from "./displayFormatters";
import { formatVehicle, isAssignmentActive } from "./fleetDocumentHelpers";
import type { BuildAdminWorkspacePropsParams } from "./buildAdminWorkspaceProps";
import type { WorkspaceContentSectionBuilderContext } from "./workspaceContentSectionBuilderContext";

export function buildAdminContentSectionParams(
  context: WorkspaceContentSectionBuilderContext,
): BuildAdminWorkspacePropsParams {
  const {
    rootState,
    authSession,
    employeesAdmin,
    servicesAdmin,
    reviewRulesAdmin,
    laborNormsAdmin,
    ocrAdmin,
    historicalImportsAdmin,
    backupsAdmin,
    navigation,
    repairWorkspaceActions,
  } = context;

  return {
    activeWorkspaceTab: rootState.activeWorkspaceTab,
    activeAdminTab: rootState.activeAdminTab,
    activeTechAdminTab: rootState.activeTechAdminTab,
    userRole: rootState.user?.role,
    adminTabDescriptions,
    handleAdminTabChange: navigation.handleAdminTabChange,
    openTechAdmin: navigation.openTechAdmin,
    techAdminTabDescriptions,
    systemStatus: ocrAdmin.systemStatus,
    handleTechAdminTabChange: navigation.handleTechAdminTabChange,
    closeTechAdmin: navigation.closeTechAdmin,
    userSearch: employeesAdmin.userSearch,
    userLoading: employeesAdmin.userLoading,
    showUserEditor: employeesAdmin.showUserEditor,
    userForm: employeesAdmin.userForm,
    userSaving: employeesAdmin.userSaving,
    usersTotal: employeesAdmin.usersTotal,
    usersList: employeesAdmin.usersList,
    selectedManagedUserId: employeesAdmin.selectedManagedUserId,
    selectedManagedUser: employeesAdmin.selectedManagedUser,
    adminResetPasswordValue: employeesAdmin.adminResetPasswordValue,
    userVehicleSearch: employeesAdmin.userVehicleSearch,
    userVehicleSearchLoading: employeesAdmin.userVehicleSearchLoading,
    userVehicleSearchResults: employeesAdmin.userVehicleSearchResults,
    userAssignmentForm: employeesAdmin.userAssignmentForm,
    userAssignmentSaving: employeesAdmin.userAssignmentSaving,
    setUserSearch: employeesAdmin.setUserSearch,
    handleUserSearch: employeesAdmin.handleUserSearch,
    resetUsersSearch: employeesAdmin.resetUsersSearch,
    setShowUserEditor: employeesAdmin.setShowUserEditor,
    updateUserFormField: employeesAdmin.updateUserFormField,
    handleSaveUser: employeesAdmin.handleSaveUser,
    resetUserEditor: employeesAdmin.resetUserEditor,
    setSelectedManagedUserId: employeesAdmin.setSelectedManagedUserId,
    editUser: employeesAdmin.editUser,
    setAdminResetPasswordValue: employeesAdmin.setAdminResetPasswordValue,
    handleAdminResetUserPassword: employeesAdmin.handleAdminResetUserPassword,
    setUserVehicleSearch: employeesAdmin.setUserVehicleSearch,
    updateUserAssignmentFormField: employeesAdmin.updateUserAssignmentFormField,
    handleSearchVehiclesForAssignment: employeesAdmin.handleSearchVehiclesForAssignment,
    handleCreateUserAssignment: employeesAdmin.handleCreateUserAssignment,
    handleCloseUserAssignment: employeesAdmin.handleCloseUserAssignment,
    formatUserRoleLabel,
    formatVehicle,
    formatVehicleTypeLabel,
    isAssignmentActive,
    serviceQuery: servicesAdmin.serviceQuery,
    serviceCityFilter: servicesAdmin.serviceCityFilter,
    serviceCities: servicesAdmin.serviceCities,
    serviceLoading: servicesAdmin.serviceLoading,
    showServiceEditor: servicesAdmin.showServiceEditor,
    serviceForm: servicesAdmin.serviceForm,
    serviceSaving: servicesAdmin.serviceSaving,
    services: servicesAdmin.services,
    showServiceListDialog: servicesAdmin.showServiceListDialog,
    setServiceQuery: servicesAdmin.setServiceQuery,
    setServiceCityFilter: servicesAdmin.setServiceCityFilter,
    handleServiceSearch: servicesAdmin.handleServiceSearch,
    resetServicesFilters: servicesAdmin.resetServicesFilters,
    setShowServiceEditor: servicesAdmin.setShowServiceEditor,
    updateServiceFormField: servicesAdmin.updateServiceFormField,
    handleSaveService: servicesAdmin.handleSaveService,
    resetServiceEditor: servicesAdmin.resetServiceEditor,
    setShowServiceListDialog: servicesAdmin.setShowServiceListDialog,
    handleEditService: repairWorkspaceActions.handleEditService,
    formatStatus,
    backupActionLoading: backupsAdmin.backupActionLoading,
    backupsLoading: backupsAdmin.backupsLoading,
    backups: backupsAdmin.backups,
    backupRestoreDialogOpen: backupsAdmin.backupRestoreDialogOpen,
    backupRestoreTarget: backupsAdmin.backupRestoreTarget,
    backupRestoreConfirmValue: backupsAdmin.backupRestoreConfirmValue,
    handleCreateBackup: backupsAdmin.handleCreateBackup,
    loadBackups: backupsAdmin.loadBackups,
    handleDownloadBackup: backupsAdmin.handleDownloadBackup,
    openBackupRestoreDialog: backupsAdmin.openBackupRestoreDialog,
    closeBackupRestoreDialog: backupsAdmin.closeBackupRestoreDialog,
    setBackupRestoreConfirmValue: backupsAdmin.setBackupRestoreConfirmValue,
    handleRestoreBackup: backupsAdmin.handleRestoreBackup,
    formatDateTime,
    formatFileSize,
    showReviewRuleEditor: reviewRulesAdmin.showReviewRuleEditor,
    reviewRuleForm: reviewRulesAdmin.reviewRuleForm,
    reviewRuleSaving: reviewRulesAdmin.reviewRuleSaving,
    reviewRules: reviewRulesAdmin.reviewRules,
    reviewRuleTypes: reviewRulesAdmin.reviewRuleTypes,
    showReviewRuleListDialog: reviewRulesAdmin.showReviewRuleListDialog,
    openReviewRulesAdmin: navigation.openReviewRulesAdmin,
    setShowReviewRuleEditor: reviewRulesAdmin.setShowReviewRuleEditor,
    updateReviewRuleFormField: reviewRulesAdmin.updateReviewRuleFormField,
    handleSaveReviewRule: reviewRulesAdmin.handleSaveReviewRule,
    resetReviewRuleEditor: reviewRulesAdmin.resetReviewRuleEditor,
    setShowReviewRuleListDialog: reviewRulesAdmin.setShowReviewRuleListDialog,
    editReviewRule: reviewRulesAdmin.editReviewRule,
    formatReviewRuleTypeLabel,
    formatReviewBucketLabel,
    ocrLearningStatusFilter: ocrAdmin.ocrLearningStatusFilter,
    ocrLearningTargetFieldFilter: ocrAdmin.ocrLearningTargetFieldFilter,
    ocrLearningProfileScopeFilter: ocrAdmin.ocrLearningProfileScopeFilter,
    ocrLearningStatuses: ocrAdmin.ocrLearningStatuses,
    ocrLearningTargetFields: ocrAdmin.ocrLearningTargetFields,
    ocrLearningProfileScopes: ocrAdmin.ocrLearningProfileScopes,
    ocrLearningLoading: ocrAdmin.ocrLearningLoading,
    ocrLearningSummaries: ocrAdmin.ocrLearningSummaries,
    ocrLearningSignals: ocrAdmin.ocrLearningSignals,
    showOcrLearningListDialog: ocrAdmin.showOcrLearningListDialog,
    ocrLearningDraftId: ocrAdmin.ocrLearningDraftId,
    ocrLearningUpdateId: ocrAdmin.ocrLearningUpdateId,
    setOcrLearningStatusFilter: ocrAdmin.setOcrLearningStatusFilter,
    setOcrLearningTargetFieldFilter: ocrAdmin.setOcrLearningTargetFieldFilter,
    setOcrLearningProfileScopeFilter: ocrAdmin.setOcrLearningProfileScopeFilter,
    token: authSession.token,
    loadOcrLearningSignals: ocrAdmin.loadOcrLearningSignals,
    setShowOcrLearningListDialog: ocrAdmin.setShowOcrLearningListDialog,
    handleLoadOcrLearningDraft: ocrAdmin.handleLoadOcrLearningDraft,
    handleUpdateOcrLearningSignal: ocrAdmin.handleUpdateOcrLearningSignal,
    formatOcrLearningStatusLabel,
    formatOcrProfileName,
    formatOcrFieldLabel,
    formatOcrSignalTypeLabel,
    ocrProfileMatcherProfileFilter: ocrAdmin.ocrProfileMatcherProfileFilter,
    ocrProfileMatcherProfiles: ocrAdmin.ocrProfileMatcherProfiles,
    ocrProfileMatchers: ocrAdmin.ocrProfileMatchers,
    ocrProfileMatcherForm: ocrAdmin.ocrProfileMatcherForm,
    ocrProfileMatcherSaving: ocrAdmin.ocrProfileMatcherSaving,
    setOcrProfileMatcherProfileFilter: ocrAdmin.setOcrProfileMatcherProfileFilter,
    loadOcrProfileMatchers: ocrAdmin.loadOcrProfileMatchers,
    updateOcrProfileMatcherFormField: ocrAdmin.updateOcrProfileMatcherFormField,
    handleSaveOcrProfileMatcher: ocrAdmin.handleSaveOcrProfileMatcher,
    resetOcrProfileMatcherEditor: ocrAdmin.resetOcrProfileMatcherEditor,
    editOcrProfileMatcher: ocrAdmin.editOcrProfileMatcher,
    formatSourceTypeLabel,
    ocrRuleProfileFilter: ocrAdmin.ocrRuleProfileFilter,
    ocrRuleProfiles: ocrAdmin.ocrRuleProfiles,
    ocrRuleTargetFields: ocrAdmin.ocrRuleTargetFields,
    ocrRules: ocrAdmin.ocrRules,
    ocrRuleForm: ocrAdmin.ocrRuleForm,
    ocrRuleSaving: ocrAdmin.ocrRuleSaving,
    setOcrRuleProfileFilter: ocrAdmin.setOcrRuleProfileFilter,
    loadOcrRules: ocrAdmin.loadOcrRules,
    updateOcrRuleFormField: ocrAdmin.updateOcrRuleFormField,
    handleSaveOcrRule: ocrAdmin.handleSaveOcrRule,
    resetOcrRuleEditor: ocrAdmin.resetOcrRuleEditor,
    editOcrRule: ocrAdmin.editOcrRule,
    formatValueParserLabel,
    historicalImportLoading: historicalImportsAdmin.historicalImportLoading,
    historicalImportFile: historicalImportsAdmin.historicalImportFile,
    historicalImportLimit: historicalImportsAdmin.historicalImportLimit,
    historicalImportResult: historicalImportsAdmin.historicalImportResult,
    historicalImportJobs: historicalImportsAdmin.historicalImportJobs,
    historicalImportJobsLoading: historicalImportsAdmin.historicalImportJobsLoading,
    historicalWorkReference: historicalImportsAdmin.historicalWorkReference,
    historicalWorkReferenceLoading: historicalImportsAdmin.historicalWorkReferenceLoading,
    historicalWorkReferenceTotal: historicalImportsAdmin.historicalWorkReferenceTotal,
    historicalWorkReferenceQuery: historicalImportsAdmin.historicalWorkReferenceQuery,
    historicalWorkReferenceMinSamples: historicalImportsAdmin.historicalWorkReferenceMinSamples,
    importConflicts: historicalImportsAdmin.importConflicts,
    importConflictsLoading: historicalImportsAdmin.importConflictsLoading,
    setHistoricalImportFile: historicalImportsAdmin.setHistoricalImportFile,
    setHistoricalImportLimit: historicalImportsAdmin.setHistoricalImportLimit,
    handleHistoricalRepairImport: historicalImportsAdmin.handleHistoricalRepairImport,
    refreshHistoricalImportsJournal: historicalImportsAdmin.refreshHistoricalImportsJournal,
    openRepairByIds: navigation.openRepairByIds,
    setHistoricalWorkReferenceQuery: historicalImportsAdmin.setHistoricalWorkReferenceQuery,
    setHistoricalWorkReferenceMinSamples: historicalImportsAdmin.setHistoricalWorkReferenceMinSamples,
    loadHistoricalWorkReference: historicalImportsAdmin.loadHistoricalWorkReference,
    openImportConflict: historicalImportsAdmin.openImportConflict,
    formatMoney,
    formatCompactNumber,
    formatHours,
    formatDateValue,
    showLaborNormCatalogEditor: laborNormsAdmin.showLaborNormCatalogEditor,
    showLaborNormImport: laborNormsAdmin.showLaborNormImport,
    showLaborNormEntryEditor: laborNormsAdmin.showLaborNormEntryEditor,
    editingLaborNormCatalogId: laborNormsAdmin.editingLaborNormCatalogId,
    laborNormCatalogForm: laborNormsAdmin.laborNormCatalogForm,
    laborNormCatalogSaving: laborNormsAdmin.laborNormCatalogSaving,
    laborNormCatalogs: laborNormsAdmin.laborNormCatalogs,
    laborNormQuery: laborNormsAdmin.laborNormQuery,
    laborNormScope: laborNormsAdmin.laborNormScope,
    laborNormScopes: laborNormsAdmin.laborNormScopes,
    laborNormCategory: laborNormsAdmin.laborNormCategory,
    laborNormCategories: laborNormsAdmin.laborNormCategories,
    laborNormLoading: laborNormsAdmin.laborNormLoading,
    laborNormImportScope: laborNormsAdmin.laborNormImportScope,
    laborNormImportBrandFamily: laborNormsAdmin.laborNormImportBrandFamily,
    laborNormImportCatalogName: laborNormsAdmin.laborNormImportCatalogName,
    laborNormFile: laborNormsAdmin.laborNormFile,
    laborNormImportLoading: laborNormsAdmin.laborNormImportLoading,
    laborNormEntryForm: laborNormsAdmin.laborNormEntryForm,
    laborNormEntrySaving: laborNormsAdmin.laborNormEntrySaving,
    laborNormTotal: laborNormsAdmin.laborNormTotal,
    laborNormSourceFiles: laborNormsAdmin.laborNormSourceFiles,
    showLaborNormListDialog: laborNormsAdmin.showLaborNormListDialog,
    laborNorms: laborNormsAdmin.laborNorms,
    openLaborNormsAdmin: navigation.openLaborNormsAdmin,
    setShowLaborNormCatalogEditor: laborNormsAdmin.setShowLaborNormCatalogEditor,
    setShowLaborNormImport: laborNormsAdmin.setShowLaborNormImport,
    setShowLaborNormEntryEditor: laborNormsAdmin.setShowLaborNormEntryEditor,
    updateLaborNormCatalogFormField: laborNormsAdmin.updateLaborNormCatalogFormField,
    handleSaveLaborNormCatalog: laborNormsAdmin.handleSaveLaborNormCatalog,
    resetLaborNormCatalogEditor: laborNormsAdmin.resetLaborNormCatalogEditor,
    editLaborNormCatalog: laborNormsAdmin.editLaborNormCatalog,
    selectCatalogScope: laborNormsAdmin.selectCatalogScope,
    setLaborNormQuery: laborNormsAdmin.setLaborNormQuery,
    setLaborNormScope: laborNormsAdmin.setLaborNormScope,
    setLaborNormCategory: laborNormsAdmin.setLaborNormCategory,
    handleLaborNormSearch: laborNormsAdmin.handleLaborNormSearch,
    resetLaborNormFilters: laborNormsAdmin.resetLaborNormFilters,
    setLaborNormImportBrandFamily: laborNormsAdmin.setLaborNormImportBrandFamily,
    setLaborNormImportCatalogName: laborNormsAdmin.setLaborNormImportCatalogName,
    setLaborNormFile: laborNormsAdmin.setLaborNormFile,
    handleLaborNormImport: laborNormsAdmin.handleLaborNormImport,
    updateLaborNormEntryFormField: laborNormsAdmin.updateLaborNormEntryFormField,
    handleSaveLaborNormEntry: laborNormsAdmin.handleSaveLaborNormEntry,
    resetLaborNormEntryEditor: laborNormsAdmin.resetLaborNormEntryEditor,
    setShowLaborNormListDialog: laborNormsAdmin.setShowLaborNormListDialog,
    editLaborNormItem: laborNormsAdmin.editLaborNormItem,
    handleArchiveLaborNormItem: laborNormsAdmin.handleArchiveLaborNormItem,
    formatCatalogCodeLabel,
  };
}
