import { documentKindOptions, historyFilters, repairTabDescriptions, workspaceTabReturnLabels } from "./appUiConfig";
import {
  checkSeverityColor,
  executiveRiskColor,
  formatCompactNumber,
  formatConfidence,
  formatConfidenceLabel,
  formatDateTime,
  formatDocumentKind,
  formatDocumentStatusLabel,
  formatExecutiveRiskLabel,
  formatHistoryActionLabel,
  formatHours,
  formatLaborNormApplicability,
  formatManualReviewReasons,
  formatMoney,
  formatOcrProfileMeta,
  formatRepairStatus,
  formatReviewPriority,
  formatSourceTypeLabel,
  formatStatus,
  formatVehicleTypeLabel,
  getConfidenceColor,
  importJobStatusColor,
  reviewPriorityColor,
  statusColor,
} from "./displayFormatters";
import { formatVehicle, isPlaceholderVehicle } from "./fleetDocumentHelpers";
import type { BuildRepairWorkspacePropsParams } from "./buildRepairWorkspaceProps";
import {
  buildCheckPayloadDetails,
  formatOcrLineUnit,
  formatWorkLaborNormMeta,
  getCheckLinkedRepairId,
  readCheckResolutionMeta,
  readNumberValue,
  readStringValue,
} from "./repairReportHelpers";
import { getReviewComparisonColor, getReviewComparisonLabel } from "./repairUiHelpers";
import {
  historyDetailFormatters,
  type WorkspaceContentSectionBuilderContext,
} from "./workspaceContentSectionBuilderContext";

export function buildRepairContentSectionParams(
  context: WorkspaceContentSectionBuilderContext,
): BuildRepairWorkspacePropsParams {
  const {
    rootState,
    documentsWorkspace,
    servicesAdmin,
    navigation,
    repairLoading,
    repairDerivedViewModel,
    repairEditingWorkflow,
    repairReviewWorkflow,
    repairWorkspaceActions,
    repairDocumentsWorkflow,
    repairHistoryFilters,
  } = context;

  return {
    repairHasReturnTarget: navigation.repairHasReturnTarget,
    workspaceTabReturnLabels,
    repairReturnTab: navigation.repairReturnTab,
    returnFromRepairPage: navigation.returnFromRepairPage,
    userRole: rootState.user?.role,
    repairLoading,
    selectedRepair: rootState.selectedRepair,
    selectedReviewItem: repairDerivedViewModel.selectedReviewItem,
    isEditingRepair: repairEditingWorkflow.isEditingRepair,
    saveRepairLoading: repairEditingWorkflow.saveRepairLoading,
    repairDraft: repairEditingWorkflow.repairDraft,
    repairExportLoading: repairWorkspaceActions.repairExportLoading,
    repairArchiveLoading: repairEditingWorkflow.repairArchiveLoading,
    repairDeleteLoading: repairEditingWorkflow.repairDeleteLoading,
    handleCancelRepairEdit: repairWorkspaceActions.handleCancelRepairEdit,
    handleSaveRepair: repairEditingWorkflow.handleSaveRepair,
    handleExportRepair: repairWorkspaceActions.handleExportRepair,
    handleStartRepairEdit: repairWorkspaceActions.handleStartRepairEdit,
    handleArchiveRepair: repairEditingWorkflow.handleArchiveRepair,
    handleDeleteRepair: repairEditingWorkflow.handleDeleteRepair,
    selectedRepairDocument: repairDerivedViewModel.selectedRepairDocument,
    reviewDocumentPreviewLoading: repairReviewWorkflow.reviewDocumentPreviewLoading,
    reviewDocumentPreviewKind: repairReviewWorkflow.reviewDocumentPreviewKind,
    reviewDocumentPreviewUrl: repairReviewWorkflow.reviewDocumentPreviewUrl,
    documentOpenLoadingId: repairDocumentsWorkflow.documentOpenLoadingId,
    canLinkVehicleFromSelectedDocument: repairDerivedViewModel.canLinkVehicleFromSelectedDocument,
    selectedRepairDocumentExtractedFields: repairDerivedViewModel.selectedRepairDocumentExtractedFields,
    reviewVehicleSearch: repairReviewWorkflow.reviewVehicleSearch,
    reviewVehicleSearchLoading: repairReviewWorkflow.reviewVehicleSearchLoading,
    reviewVehicleLinkingId: repairReviewWorkflow.reviewVehicleLinkingId,
    reviewVehicleSearchResults: repairReviewWorkflow.reviewVehicleSearchResults,
    selectedRepairDocumentOcrServiceName: repairDerivedViewModel.selectedRepairDocumentOcrServiceName,
    reviewServiceName: repairReviewWorkflow.reviewServiceName,
    services: servicesAdmin.services,
    reviewServiceAssigning: repairReviewWorkflow.reviewServiceAssigning,
    reviewServiceSaving: repairReviewWorkflow.reviewServiceSaving,
    reviewFieldSaving: repairReviewWorkflow.reviewFieldSaving,
    showReviewServiceEditor: repairReviewWorkflow.showReviewServiceEditor,
    reviewServiceForm: repairReviewWorkflow.reviewServiceForm,
    canConfirmSelectedReview: repairDerivedViewModel.canConfirmSelectedReview,
    reviewReadyFieldsCount: repairDerivedViewModel.reviewReadyFieldsCount,
    reviewRequiredFieldComparisons: repairDerivedViewModel.reviewRequiredFieldComparisons,
    showReviewFieldEditor: repairReviewWorkflow.showReviewFieldEditor,
    setShowReviewFieldEditor: repairReviewWorkflow.setShowReviewFieldEditor,
    reviewFieldDraft: repairReviewWorkflow.reviewFieldDraft,
    reviewMissingRequiredFields: repairDerivedViewModel.reviewMissingRequiredFields,
    selectedRepairDocumentFieldSnapshots: repairDerivedViewModel.selectedRepairDocumentFieldSnapshots,
    selectedRepairDocumentPayload: repairDerivedViewModel.selectedRepairDocumentPayload,
    selectedRepairDocumentWorks: repairDerivedViewModel.selectedRepairDocumentWorks,
    selectedRepairDocumentParts: repairDerivedViewModel.selectedRepairDocumentParts,
    reviewActionComment: repairReviewWorkflow.reviewActionComment,
    reviewActionLoading: repairReviewWorkflow.reviewActionLoading,
    canCreateVehicleFromSelectedDocument: repairDerivedViewModel.canCreateVehicleFromSelectedDocument,
    documentVehicleForm: rootState.documentVehicleForm,
    documentVehicleSaving: repairWorkspaceActions.documentVehicleSaving,
    handleOpenDocumentFile: repairDocumentsWorkflow.handleOpenDocumentFile,
    setReviewVehicleSearch: repairReviewWorkflow.setReviewVehicleSearch,
    handleSearchReviewVehicles: repairReviewWorkflow.handleSearchReviewVehicles,
    handleLinkReviewVehicle: repairReviewWorkflow.handleLinkReviewVehicle,
    setReviewServiceName: repairReviewWorkflow.setReviewServiceName,
    setShowReviewServiceEditor: repairReviewWorkflow.setShowReviewServiceEditor,
    setReviewServiceForm: repairReviewWorkflow.setReviewServiceForm,
    assignReviewService: repairReviewWorkflow.assignReviewService,
    handleAssignReviewService: repairReviewWorkflow.handleAssignReviewService,
    handleCreateReviewService: repairReviewWorkflow.handleCreateReviewService,
    fillReviewFieldDraftFromOcr: repairReviewWorkflow.fillReviewFieldDraftFromOcr,
    updateReviewFieldDraft: repairReviewWorkflow.updateReviewFieldDraft,
    handleSaveReviewFields: repairReviewWorkflow.handleSaveReviewFields,
    setReviewActionComment: repairReviewWorkflow.setReviewActionComment,
    handleReviewAction: repairReviewWorkflow.handleReviewAction,
    setDocumentVehicleForm: rootState.setDocumentVehicleForm,
    handleCreateVehicleFromDocument: repairWorkspaceActions.handleCreateVehicleFromDocument,
    getReviewComparisonColor,
    getReviewComparisonLabel,
    getConfidenceColor,
    formatConfidenceLabel,
    formatMoney,
    formatCompactNumber,
    formatHours,
    formatManualReviewReasons,
    formatOcrProfileMeta,
    formatLaborNormApplicability,
    readStringValue,
    readNumberValue,
    formatOcrLineUnit,
    formatDocumentKind,
    statusColor,
    formatDocumentStatusLabel,
    formatDateTime,
    formatSourceTypeLabel,
    formatConfidence,
    formatVehicle,
    formatVehicleTypeLabel,
    activeRepairTab: rootState.activeRepairTab,
    repairTabDescriptions,
    handleRepairTabChange: navigation.handleRepairTabChange,
    updateRepairDraftField: repairEditingWorkflow.updateRepairDraftField,
    addWorkDraft: repairEditingWorkflow.addWorkDraft,
    updateWorkDraft: repairEditingWorkflow.updateWorkDraft,
    removeWorkDraft: repairEditingWorkflow.removeWorkDraft,
    addPartDraft: repairEditingWorkflow.addPartDraft,
    updatePartDraft: repairEditingWorkflow.updatePartDraft,
    removePartDraft: repairEditingWorkflow.removePartDraft,
    selectedRepairAwaitingOcr: repairDerivedViewModel.selectedRepairAwaitingOcr,
    selectedRepairUnresolvedChecks: repairDerivedViewModel.selectedRepairUnresolvedChecks,
    selectedRepairHasBlockingFindings: repairDerivedViewModel.selectedRepairHasBlockingFindings,
    selectedRepairComparisonAttentionCount: repairDerivedViewModel.selectedRepairComparisonAttentionCount,
    selectedRepairDocumentManualReviewReasons: repairDerivedViewModel.selectedRepairDocumentManualReviewReasons,
    selectedRepairReportSections: repairDerivedViewModel.selectedRepairReportSections,
    showRepairOverviewDetails: rootState.showRepairOverviewDetails,
    setShowRepairOverviewDetails: rootState.setShowRepairOverviewDetails,
    openRepairByIds: navigation.openRepairByIds,
    isPlaceholderVehicle,
    formatRepairStatus,
    executiveRiskColor,
    formatExecutiveRiskLabel,
    buildCheckPayloadDetails,
    getCheckLinkedRepairId,
    checkSeverityColor,
    formatStatus,
    documentKindOptions,
    attachedDocumentKind: repairDocumentsWorkflow.attachedDocumentKind,
    attachedDocumentNotes: repairDocumentsWorkflow.attachedDocumentNotes,
    attachedDocumentFile: repairDocumentsWorkflow.attachedDocumentFile,
    attachedFileInputRef: rootState.attachedFileInputRef,
    attachDocumentLoading: repairDocumentsWorkflow.attachDocumentLoading,
    reprocessLoading: documentsWorkspace.reprocessLoading,
    selectedDocumentId: rootState.selectedDocumentId,
    documentComparisonLoadingId: repairDocumentsWorkflow.documentComparisonLoadingId,
    primaryDocumentLoadingId: repairDocumentsWorkflow.primaryDocumentLoadingId,
    documentArchiveLoadingId: documentsWorkspace.documentArchiveLoadingId,
    documentComparison: repairDocumentsWorkflow.documentComparison,
    documentComparisonComment: repairDocumentsWorkflow.documentComparisonComment,
    documentComparisonReviewLoading: repairDocumentsWorkflow.documentComparisonReviewLoading,
    setAttachedDocumentKind: repairDocumentsWorkflow.setAttachedDocumentKind,
    setAttachedDocumentNotes: repairDocumentsWorkflow.setAttachedDocumentNotes,
    setAttachedDocumentFile: repairDocumentsWorkflow.setAttachedDocumentFile,
    handleAttachDocumentToRepair: repairDocumentsWorkflow.handleAttachDocumentToRepair,
    handleReprocessDocumentById: documentsWorkspace.handleReprocessDocumentById,
    handleCompareWithPrimary: repairDocumentsWorkflow.handleCompareWithPrimary,
    handleSetPrimaryDocument: repairDocumentsWorkflow.handleSetPrimaryDocument,
    handleArchiveDocument: documentsWorkspace.handleArchiveDocument,
    setDocumentComparison: repairDocumentsWorkflow.setDocumentComparison,
    setDocumentComparisonComment: repairDocumentsWorkflow.setDocumentComparisonComment,
    handleReviewDocumentComparison: repairDocumentsWorkflow.handleReviewDocumentComparison,
    importJobStatusColor,
    filteredDocumentHistory: repairHistoryFilters.filteredDocumentHistory,
    filteredRepairHistory: repairHistoryFilters.filteredRepairHistory,
    historySearch: rootState.historySearch,
    historyFilter: rootState.historyFilter,
    historyFilters,
    checkComments: rootState.checkComments,
    checkActionLoadingId: repairWorkspaceActions.checkActionLoadingId,
    setHistorySearch: rootState.setHistorySearch,
    setHistoryFilter: rootState.setHistoryFilter,
    setCheckComments: rootState.setCheckComments,
    handleCheckResolution: repairWorkspaceActions.handleCheckResolution,
    formatWorkLaborNormMeta,
    readCheckResolutionMeta,
    formatHistoryActionLabel,
    historyDetailFormatters,
    reviewPriorityColor,
    formatReviewPriority,
  };
}
