import {
  formatAuditEntityLabel,
  formatConfidence,
  formatDateTime,
  formatDateValue,
  formatDocumentStatusLabel,
  formatHistoryActionLabel,
  formatMoney,
  formatRepairStatus,
  formatUserRoleLabel,
  formatVehicleStatusLabel,
  formatVehicleTypeLabel,
  statusColor,
  vehicleStatusColor,
} from "./displayFormatters";
import { formatVehicle } from "./fleetDocumentHelpers";
import type { BuildOperationsWorkspacePropsParams } from "./buildOperationsWorkspaceProps";
import {
  historyDetailFormatters,
  type WorkspaceContentSectionBuilderContext,
} from "./workspaceContentSectionBuilderContext";

export function buildOperationsContentSectionParams(
  context: WorkspaceContentSectionBuilderContext,
): BuildOperationsWorkspacePropsParams {
  const { rootState, employeesAdmin, operationsWorkspace, fleetWorkspace, navigation } = context;

  return {
    activeWorkspaceTab: rootState.activeWorkspaceTab,
    globalSearchQuery: operationsWorkspace.globalSearchQuery,
    globalSearchLoading: operationsWorkspace.globalSearchLoading,
    globalSearchResult: operationsWorkspace.globalSearchResult,
    setGlobalSearchQuery: operationsWorkspace.setGlobalSearchQuery,
    handleGlobalSearchSubmit: operationsWorkspace.handleGlobalSearchSubmit,
    resetGlobalSearch: operationsWorkspace.resetGlobalSearch,
    openRepairByIds: navigation.openRepairByIds,
    openFleetVehicleById: fleetWorkspace.openFleetVehicleById,
    setActiveWorkspaceTab: rootState.setActiveWorkspaceTab,
    updateBrowserRoute: navigation.updateBrowserRoute,
    statusColor,
    vehicleStatusColor,
    formatDocumentStatusLabel,
    formatRepairStatus,
    formatVehicleTypeLabel,
    formatVehicleStatusLabel,
    formatConfidence,
    formatDateTime,
    formatMoney,
    userRole: rootState.user?.role,
    auditSearchQuery: operationsWorkspace.auditSearchQuery,
    auditEntityTypeFilter: operationsWorkspace.auditEntityTypeFilter,
    auditActionTypeFilter: operationsWorkspace.auditActionTypeFilter,
    auditUserIdFilter: operationsWorkspace.auditUserIdFilter,
    auditDateFrom: operationsWorkspace.auditDateFrom,
    auditDateTo: operationsWorkspace.auditDateTo,
    auditEntityTypes: operationsWorkspace.auditEntityTypes,
    auditActionTypes: operationsWorkspace.auditActionTypes,
    usersList: employeesAdmin.usersList,
    auditLogLoading: operationsWorkspace.auditLogLoading,
    auditLogItems: operationsWorkspace.auditLogItems,
    auditLogTotal: operationsWorkspace.auditLogTotal,
    setAuditSearchQuery: operationsWorkspace.setAuditSearchQuery,
    setAuditEntityTypeFilter: operationsWorkspace.setAuditEntityTypeFilter,
    setAuditActionTypeFilter: operationsWorkspace.setAuditActionTypeFilter,
    setAuditUserIdFilter: operationsWorkspace.setAuditUserIdFilter,
    setAuditDateFrom: operationsWorkspace.setAuditDateFrom,
    setAuditDateTo: operationsWorkspace.setAuditDateTo,
    loadAuditLog: operationsWorkspace.loadAuditLog,
    resetAudit: operationsWorkspace.resetAudit,
    formatAuditEntityLabel,
    formatHistoryActionLabel,
    historyDetailFormatters,
    fleetViewMode: fleetWorkspace.fleetViewMode,
    selectedFleetVehicleLoading: fleetWorkspace.selectedFleetVehicleLoading,
    selectedFleetVehicle: fleetWorkspace.selectedFleetVehicle,
    vehicleSaving: fleetWorkspace.vehicleSaving,
    vehicleExportLoading: fleetWorkspace.vehicleExportLoading,
    vehicles: rootState.vehicles,
    fleetVehicles: fleetWorkspace.fleetVehicles,
    handleUpdateVehicle: fleetWorkspace.handleUpdateVehicle,
    handleExportVehicle: fleetWorkspace.handleExportVehicle,
    formatVehicle,
    formatDateValue,
    formatUserRoleLabel,
    fleetQuery: fleetWorkspace.fleetQuery,
    fleetVehicleTypeFilter: fleetWorkspace.fleetVehicleTypeFilter,
    fleetStatusFilter: fleetWorkspace.fleetStatusFilter,
    fleetVehiclesTotal: fleetWorkspace.fleetVehiclesTotal,
    selectedFleetVehicleId: fleetWorkspace.selectedFleetVehicleId,
    fleetLoading: fleetWorkspace.fleetLoading,
    setFleetQuery: fleetWorkspace.setFleetQuery,
    setFleetVehicleTypeFilter: fleetWorkspace.setFleetVehicleTypeFilter,
    setFleetStatusFilter: fleetWorkspace.setFleetStatusFilter,
    loadFleetVehicles: fleetWorkspace.loadFleetVehicles,
    returnToFleetList: fleetWorkspace.returnToFleetList,
    openFleetVehicleCard: fleetWorkspace.openFleetVehicleCard,
  };
}
