import { rootDocumentKindOptions, reviewQueueFilters } from "./appUiConfig";
import {
  formatConfidence,
  formatDocumentKind,
  formatDocumentStatusLabel,
  formatLaborNormApplicability,
  formatManualReviewReasons,
  formatMoney,
  formatOcrProfileMeta,
  formatReviewPriority,
  formatStatus,
  importJobStatusColor,
  isDocumentAwaitingOcr,
  reviewPriorityColor,
  statusColor,
} from "./displayFormatters";
import { documentHasActiveImportJob } from "./displayFormatters";
import { formatVehicle, isPlaceholderVehicle } from "./fleetDocumentHelpers";
import type { BuildDocumentsWorkspacePropsParams } from "./buildDocumentsWorkspaceProps";
import type { WorkspaceContentSectionBuilderContext } from "./workspaceContentSectionBuilderContext";

export function buildDocumentsContentSectionParams(
  context: WorkspaceContentSectionBuilderContext,
): BuildDocumentsWorkspacePropsParams {
  const {
    rootState,
    documentsWorkspace,
    navigation,
    repairDerivedViewModel,
    repairEditingWorkflow,
    repairWorkspaceActions,
  } = context;

  return {
    activeWorkspaceTab: rootState.activeWorkspaceTab,
    uploadForm: documentsWorkspace.uploadForm,
    vehicles: rootState.vehicles,
    rootDocumentKindOptions,
    selectedFile: documentsWorkspace.selectedFile,
    uploadMissingRequirements: repairDerivedViewModel.uploadMissingRequirements,
    uploadLoading: documentsWorkspace.uploadLoading,
    lastUploadedDocument: documentsWorkspace.lastUploadedDocument,
    uploadFileInputRef: documentsWorkspace.uploadFileInputRef,
    handleUpload: documentsWorkspace.handleUpload,
    updateUploadFormField: documentsWorkspace.updateUploadFormField,
    handleUploadFileSelect: documentsWorkspace.handleUploadFileSelect,
    openRepairByIds: navigation.openRepairByIds,
    setLastUploadedDocument: documentsWorkspace.setLastUploadedDocument,
    formatVehicle,
    formatDocumentKind,
    importJobStatusColor,
    formatStatus,
    statusColor,
    formatDocumentStatusLabel,
    isDocumentAwaitingOcr,
    documentHasActiveImportJob,
    isPlaceholderVehicle,
    formatConfidence,
    reviewQueueFilters,
    reviewQueueCounts: rootState.reviewQueueCounts,
    selectedReviewCategory: rootState.selectedReviewCategory,
    reviewQueue: rootState.reviewQueue,
    userRole: rootState.user?.role,
    reprocessLoading: documentsWorkspace.reprocessLoading,
    selectedDocumentId: rootState.selectedDocumentId,
    setSelectedReviewCategory: rootState.setSelectedReviewCategory,
    handleOpenRepair: repairWorkspaceActions.handleOpenRepair,
    handleReprocessDocumentById: documentsWorkspace.handleReprocessDocumentById,
    reviewPriorityColor,
    formatReviewPriority,
    formatMoney,
    documents: rootState.documents,
    batchReprocessLimit: documentsWorkspace.batchReprocessLimit,
    batchReprocessStatusFilter: documentsWorkspace.batchReprocessStatusFilter,
    batchReprocessPrimaryOnly: documentsWorkspace.batchReprocessPrimaryOnly,
    batchReprocessLoading: documentsWorkspace.batchReprocessLoading,
    repairDeleteLoading: repairEditingWorkflow.repairDeleteLoading,
    documentArchiveLoadingId: documentsWorkspace.documentArchiveLoadingId,
    setBatchReprocessLimit: documentsWorkspace.setBatchReprocessLimit,
    setBatchReprocessStatusFilter: documentsWorkspace.setBatchReprocessStatusFilter,
    setBatchReprocessPrimaryOnly: documentsWorkspace.setBatchReprocessPrimaryOnly,
    handleBatchReprocessDocuments: documentsWorkspace.handleBatchReprocessDocuments,
    handleReprocessDocument: documentsWorkspace.handleReprocessDocument,
    handleDeleteRepair: repairEditingWorkflow.handleDeleteRepair,
    handleArchiveDocument: documentsWorkspace.handleArchiveDocument,
    formatManualReviewReasons,
    formatOcrProfileMeta,
    formatLaborNormApplicability,
  };
}
