import { AuthLandingView } from "./components/AuthLandingView";
import { WorkspaceMainView } from "./components/WorkspaceMainView";
import { useAppBridgeCallbacks } from "./hooks/useAppBridgeCallbacks";
import { useAppNavigation } from "./hooks/useAppNavigation";
import { useAppRootState } from "./hooks/useAppRootState";
import { useAuthSession } from "./hooks/useAuthSession";
import { useBackupsAdmin } from "./hooks/useBackupsAdmin";
import { useDocumentsWorkspace } from "./hooks/useDocumentsWorkspace";
import { useEmployeesAdmin } from "./hooks/useEmployeesAdmin";
import { useLaborNormsAdmin } from "./hooks/useLaborNormsAdmin";
import { useOcrAdmin } from "./hooks/useOcrAdmin";
import { useReviewRulesAdmin } from "./hooks/useReviewRulesAdmin";
import { useRepairDerivedViewModel } from "./hooks/useRepairDerivedViewModel";
import { useRepairDetailLoader } from "./hooks/useRepairDetailLoader";
import { useRepairDocumentsWorkflow } from "./hooks/useRepairDocumentsWorkflow";
import { useRepairEditingWorkflow } from "./hooks/useRepairEditingWorkflow";
import { useRepairHistoryFilters } from "./hooks/useRepairHistoryFilters";
import { useRepairWorkspaceActions } from "./hooks/useRepairWorkspaceActions";
import { useFleetWorkspace } from "./hooks/useFleetWorkspace";
import { useHistoricalImportsAdmin } from "./hooks/useHistoricalImportsAdmin";
import { useRepairReviewWorkflow } from "./hooks/useRepairReviewWorkflow";
import { useRepairPresentationState } from "./hooks/useRepairPresentationState";
import { useServicesAdmin } from "./hooks/useServicesAdmin";
import { useWorkspaceDataLifecycle } from "./hooks/useWorkspaceDataLifecycle";
import { useWorkspaceOperations } from "./hooks/useWorkspaceOperations";
import { formatVehicle } from "./shared/fleetDocumentHelpers";
import { buildAuthLandingProps } from "./shared/buildAuthLandingProps";
import { buildWorkspaceLifecycleAdapters } from "./shared/buildWorkspaceLifecycleAdapters";
import { buildWorkspaceMainViewProps } from "./shared/buildWorkspaceMainViewProps";
import {
  formatConfidence,
  formatDateTime,
  formatDocumentKind,
  formatDocumentStatusLabel,
  formatMoney,
  formatRepairStatus,
  formatStatus,
  isDocumentAwaitingOcr,
} from "./shared/displayFormatters";
import {
  createEmptyDocumentVehicleForm,
  createEmptyUploadForm,
} from "./shared/formStateFactories";
import {
  VEHICLES_FULL_LIST_LIMIT,
} from "./shared/appUiConfig";
import type { RepairDetail } from "./shared/repairDetailTypes";
import type { DocumentItem } from "./shared/workspaceBootstrapTypes";

// Predeploy marker: uploaded: "В очереди OCR"

export default function App() {
  const appRootState = useAppRootState({
    createEmptyDocumentVehicleForm,
  });
  const {
    user,
    setUser,
    activeWorkspaceTab,
    setActiveWorkspaceTab,
    activeAdminTab,
    setActiveAdminTab,
    activeTechAdminTab,
    setActiveTechAdminTab,
    activeRepairTab,
    setActiveRepairTab,
    activeQualityTab,
    setActiveQualityTab,
    showQualityDialog,
    setShowQualityDialog,
    showTechAdminTab,
    setShowTechAdminTab,
    summary,
    setSummary,
    dataQuality,
    setDataQuality,
    dataQualityDetails,
    setDataQualityDetails,
    vehicles,
    setVehicles,
    documents,
    setDocuments,
    reviewQueue,
    setReviewQueue,
    reviewQueueCounts,
    setReviewQueueCounts,
    selectedReviewCategory,
    setSelectedReviewCategory,
    selectedDocumentId,
    setSelectedDocumentId,
    selectedRepair,
    setSelectedRepair,
    documentVehicleForm,
    setDocumentVehicleForm,
    attachedFileInputRef,
    checkComments,
    setCheckComments,
    historyFilter,
    setHistoryFilter,
    historySearch,
    setHistorySearch,
    showRepairOverviewDetails,
    setShowRepairOverviewDetails,
    errorMessage,
    setErrorMessage,
    successMessage,
    setSuccessMessage,
    isEditingRepairRef,
    syncRepairDraftFromRepairRef,
    resetRepairDocumentsWorkflowStateRef,
  } = appRootState;

  const authSession = useAuthSession({
    setErrorMessage,
    setSuccessMessage,
    onLogoutAppReset: () => {
      setActiveWorkspaceTab("documents");
      setActiveAdminTab("services");
      setActiveTechAdminTab("learning");
      setActiveRepairTab("overview");
      setShowTechAdminTab(false);
      setLastUploadedDocument(null);
      resetRepairDocumentsWorkflowStateRef.current();
    },
  });
  const {
    token,
    showPasswordChange,
    setShowPasswordChange,
    showPasswordRecoveryRequest,
    loginValue,
    setLoginValue,
    passwordValue,
    setPasswordValue,
    currentPasswordValue,
    setCurrentPasswordValue,
    newPasswordValue,
    setNewPasswordValue,
    recoveryEmailValue,
    setRecoveryEmailValue,
    recoveryTokenValue,
    setRecoveryTokenValue,
    recoveryNewPasswordValue,
    setRecoveryNewPasswordValue,
    loginLoading,
    passwordChangeLoading,
    passwordRecoveryLoading,
    invalidateSession,
    handleLogin,
    handleChangePassword,
    handleRequestPasswordRecovery,
    handleConfirmPasswordRecovery,
    openPasswordRecovery,
    handleBackToLogin,
    cancelPasswordChange,
    handleLogout,
  } = authSession;
  const {
    openRepairByIdsRef,
    openTechAdminRef,
    openReviewRulesAdminRef,
    openLaborNormsAdminRef,
    loadWorkspaceRef,
    openRepairByIdsFromDocuments,
    openTechAdmin,
    openReviewRulesAdmin,
    openLaborNormsAdmin,
    refreshWorkspace,
  } = useAppBridgeCallbacks(token);
  const documentsWorkspace = useDocumentsWorkspace({
    token,
    userRole: user?.role,
    emptyUploadForm: createEmptyUploadForm,
    setErrorMessage,
    setSuccessMessage,
    refreshWorkspace,
    openRepairByIds: openRepairByIdsFromDocuments,
    selectedDocumentId,
    selectedRepairId: selectedRepair?.id ?? null,
    formatDocumentStatusLabel,
  });
  const {
    uploadForm,
    selectedFile,
    lastUploadedDocument,
    setLastUploadedDocument,
    uploadFileInputRef,
    uploadLoading,
    reprocessLoading,
    batchReprocessLoading,
    batchReprocessLimit,
    setBatchReprocessLimit,
    batchReprocessStatusFilter,
    setBatchReprocessStatusFilter,
    batchReprocessPrimaryOnly,
    setBatchReprocessPrimaryOnly,
    documentArchiveLoadingId,
    handleUpload,
    updateUploadFormField,
    handleUploadFileSelect,
    handleReprocessDocumentById,
    handleReprocessDocument,
    handleBatchReprocessDocuments,
    handleArchiveDocument,
    resetDocumentsWorkspaceState,
  } = documentsWorkspace;
  const employeesAdmin = useEmployeesAdmin({
    token,
    userRole: user?.role,
    setErrorMessage,
    setSuccessMessage,
  });
  const {
    usersList,
    usersTotal,
    userLoading,
    userSaving,
    userSearch,
    setUserSearch,
    showUserEditor,
    setShowUserEditor,
    userForm,
    selectedManagedUserId,
    setSelectedManagedUserId,
    selectedManagedUser,
    adminResetPasswordValue,
    setAdminResetPasswordValue,
    userVehicleSearch,
    setUserVehicleSearch,
    userVehicleSearchLoading,
    userVehicleSearchResults,
    userAssignmentForm,
    userAssignmentSaving,
    applyBootstrapUsers,
    resetUserEditor,
    editUser,
    updateUserFormField,
    updateUserAssignmentFormField,
    handleUserSearch,
    resetUsersSearch,
    handleSaveUser,
    handleSearchVehiclesForAssignment,
    handleCreateUserAssignment,
    handleAdminResetUserPassword,
    handleCloseUserAssignment,
    resetUsersState,
  } = employeesAdmin;
  const servicesAdmin = useServicesAdmin({
    token,
    userRole: user?.role,
    setErrorMessage,
    setSuccessMessage,
  });
  const {
    services,
    serviceCities,
    serviceQuery,
    setServiceQuery,
    serviceCityFilter,
    setServiceCityFilter,
    serviceLoading,
    serviceSaving,
    serviceForm,
    showServiceEditor,
    setShowServiceEditor,
    showServiceListDialog,
    setShowServiceListDialog,
    applyBootstrapServices,
    loadServices,
    updateServiceFormField,
    editService,
    resetServiceEditor,
    handleServiceSearch,
    resetServicesFilters,
    handleSaveService,
    resetServicesState,
  } = servicesAdmin;
  const reviewRulesAdmin = useReviewRulesAdmin({
    token,
    userRole: user?.role,
    setErrorMessage,
    setSuccessMessage,
    openReviewRulesAdmin,
  });
  const {
    showReviewRuleEditor,
    setShowReviewRuleEditor,
    showReviewRuleListDialog,
    setShowReviewRuleListDialog,
    reviewRules,
    reviewRuleTypes,
    reviewRuleSaving,
    reviewRuleForm,
    applyBootstrapReviewRules,
    updateReviewRuleFormField,
    editReviewRule,
    resetReviewRuleEditor,
    handleSaveReviewRule,
    resetReviewRulesState,
  } = reviewRulesAdmin;
  const laborNormsAdmin = useLaborNormsAdmin({
    token,
    userRole: user?.role,
    setErrorMessage,
    setSuccessMessage,
    openLaborNormsAdmin,
  });
  const {
    showLaborNormCatalogEditor,
    setShowLaborNormCatalogEditor,
    showLaborNormImport,
    setShowLaborNormImport,
    showLaborNormEntryEditor,
    setShowLaborNormEntryEditor,
    showLaborNormListDialog,
    setShowLaborNormListDialog,
    laborNorms,
    laborNormCatalogs,
    laborNormTotal,
    laborNormScopes,
    laborNormCategories,
    laborNormSourceFiles,
    laborNormQuery,
    setLaborNormQuery,
    laborNormScope,
    setLaborNormScope,
    laborNormCategory,
    setLaborNormCategory,
    laborNormLoading,
    laborNormImportLoading,
    laborNormFile,
    setLaborNormFile,
    laborNormImportScope,
    laborNormImportBrandFamily,
    setLaborNormImportBrandFamily,
    laborNormImportCatalogName,
    setLaborNormImportCatalogName,
    laborNormCatalogSaving,
    laborNormEntrySaving,
    editingLaborNormCatalogId,
    laborNormCatalogForm,
    laborNormEntryForm,
    applyBootstrapLaborNorms,
    updateLaborNormCatalogFormField,
    handleLaborNormSearch,
    resetLaborNormFilters,
    handleLaborNormImport,
    editLaborNormCatalog,
    resetLaborNormCatalogEditor,
    selectCatalogScope,
    handleSaveLaborNormCatalog,
    updateLaborNormEntryFormField,
    editLaborNormItem,
    resetLaborNormEntryEditor,
    handleSaveLaborNormEntry,
    handleArchiveLaborNormItem,
    resetLaborNormsState,
  } = laborNormsAdmin;
  const ocrAdmin = useOcrAdmin({
    token,
    userRole: user?.role,
    setErrorMessage,
    setSuccessMessage,
    openTechAdmin,
  });
  const {
    ocrRules,
    ocrRuleProfiles,
    ocrRuleTargetFields,
    ocrRuleProfileFilter,
    setOcrRuleProfileFilter,
    ocrRuleSaving,
    ocrRuleForm,
    ocrProfileMatchers,
    ocrProfileMatcherProfiles,
    ocrProfileMatcherProfileFilter,
    setOcrProfileMatcherProfileFilter,
    ocrProfileMatcherSaving,
    ocrProfileMatcherForm,
    ocrLearningSignals,
    ocrLearningSummaries,
    ocrLearningStatuses,
    ocrLearningTargetFields,
    ocrLearningProfileScopes,
    systemStatus,
    ocrLearningStatusFilter,
    setOcrLearningStatusFilter,
    ocrLearningTargetFieldFilter,
    setOcrLearningTargetFieldFilter,
    ocrLearningProfileScopeFilter,
    setOcrLearningProfileScopeFilter,
    showOcrLearningListDialog,
    setShowOcrLearningListDialog,
    ocrLearningLoading,
    ocrLearningUpdateId,
    ocrLearningDraftId,
    applyBootstrapOcrAdmin,
    loadOcrRules,
    loadOcrProfileMatchers,
    loadOcrLearningSignals,
    updateOcrRuleFormField,
    editOcrRule,
    resetOcrRuleEditor,
    handleSaveOcrRule,
    updateOcrProfileMatcherFormField,
    editOcrProfileMatcher,
    resetOcrProfileMatcherEditor,
    handleSaveOcrProfileMatcher,
    handleUpdateOcrLearningSignal,
    handleLoadOcrLearningDraft,
    resetOcrAdminState,
  } = ocrAdmin;
  const historicalImportsAdmin = useHistoricalImportsAdmin({
    token,
    userRole: user?.role,
    activeWorkspaceTab,
    activeAdminTab,
    setErrorMessage,
    setSuccessMessage,
    refreshWorkspace,
  });
  const {
    historicalImportLoading,
    historicalImportFile,
    setHistoricalImportFile,
    historicalImportLimit,
    setHistoricalImportLimit,
    historicalImportResult,
    historicalImportJobs,
    historicalImportJobsLoading,
    historicalWorkReference,
    historicalWorkReferenceLoading,
    historicalWorkReferenceTotal,
    historicalWorkReferenceQuery,
    setHistoricalWorkReferenceQuery,
    historicalWorkReferenceMinSamples,
    setHistoricalWorkReferenceMinSamples,
    importConflicts,
    importConflictsLoading,
    selectedImportConflict,
    showImportConflictDialog,
    importConflictLoading,
    importConflictSaving,
    importConflictComment,
    setImportConflictComment,
    setShowImportConflictDialog,
    loadHistoricalWorkReference,
    refreshHistoricalImportsJournal,
    openImportConflict,
    handleHistoricalRepairImport,
    handleResolveImportConflict,
    resetHistoricalImportsState,
  } = historicalImportsAdmin;
  const workspaceOperations = useWorkspaceOperations({
    activeWorkspaceTab,
    token,
    onError: setErrorMessage,
  });
  const {
    globalSearchQuery,
    setGlobalSearchQuery,
    globalSearchLoading,
    globalSearchResult,
    handleGlobalSearchSubmit,
    resetGlobalSearch,
    auditLogItems,
    auditLogLoading,
    auditLogTotal,
    auditEntityTypes,
    auditActionTypes,
    auditSearchQuery,
    setAuditSearchQuery,
    auditEntityTypeFilter,
    setAuditEntityTypeFilter,
    auditActionTypeFilter,
    setAuditActionTypeFilter,
    auditUserIdFilter,
    setAuditUserIdFilter,
    auditDateFrom,
    setAuditDateFrom,
    auditDateTo,
    setAuditDateTo,
    loadAuditLog,
    resetAudit,
    resetOperationsState,
  } = workspaceOperations;
  const backupsAdmin = useBackupsAdmin({
    token,
    userRole: user?.role,
    activeWorkspaceTab,
    activeAdminTab,
    setErrorMessage,
    setSuccessMessage,
  });
  const {
    backups,
    backupsLoading,
    backupActionLoading,
    backupRestoreDialogOpen,
    backupRestoreTarget,
    backupRestoreConfirmValue,
    setBackupRestoreConfirmValue,
    loadBackups,
    openBackupRestoreDialog,
    closeBackupRestoreDialog,
    handleCreateBackup,
    handleDownloadBackup,
    handleRestoreBackup,
    resetBackupsState,
  } = backupsAdmin;
  const fleetWorkspace = useFleetWorkspace({
    token,
    activeWorkspaceTab,
    vehiclesFullListLimit: VEHICLES_FULL_LIST_LIMIT,
    setErrorMessage,
    setSuccessMessage,
  });
  const {
    fleetVehicles,
    fleetVehiclesTotal,
    fleetLoading,
    fleetQuery,
    setFleetQuery,
    fleetVehicleTypeFilter,
    setFleetVehicleTypeFilter,
    fleetStatusFilter,
    setFleetStatusFilter,
    selectedFleetVehicleId,
    setSelectedFleetVehicleId,
    selectedFleetVehicle,
    selectedFleetVehicleLoading,
    fleetViewMode,
    setFleetViewMode,
    vehicleSaving,
    vehicleExportLoading,
    loadFleetVehicles,
    applyBootstrapVehicleList,
    openFleetVehicleCard,
    returnToFleetList,
    openFleetVehicleById,
    handleUpdateVehicle,
    handleExportVehicle,
    resetFleetState,
  } = fleetWorkspace;
  const repairDetailLoader = useRepairDetailLoader<RepairDetail, DocumentItem>({
    setErrorMessage,
    setSelectedRepair,
    setSelectedDocumentId,
    setLastUploadedDocument,
    setCheckComments,
    setHistoryFilter,
    setHistorySearch,
    isEditingRepairRef,
    syncRepairDraftFromRepairRef,
    resetRepairDocumentsWorkflowStateRef,
  });
  const { repairLoading, loadRepairDetail } = repairDetailLoader;
  const appNavigation = useAppNavigation({
    userRole: user?.role,
    token,
    activeWorkspaceTab,
    setActiveWorkspaceTab,
    activeAdminTab,
    setActiveAdminTab,
    activeTechAdminTab,
    setActiveTechAdminTab,
    activeRepairTab,
    setActiveRepairTab,
    showTechAdminTab,
    setShowTechAdminTab,
    fleetViewMode,
    setFleetViewMode,
    selectedFleetVehicleId,
    setSelectedFleetVehicleId,
    selectedRepairId: selectedRepair?.id ?? null,
    selectedDocumentId,
    setSelectedDocumentId,
    loadRepairDetail,
  });
  const {
    repairHasReturnTarget,
    repairReturnTab,
    updateBrowserRoute,
    handleWorkspaceTabChange,
    handleAdminTabChange,
    handleTechAdminTabChange,
    handleRepairTabChange,
    openAdminTab,
    openTechAdmin: openTechAdminInternal,
    closeTechAdmin,
    openReviewRulesAdmin: openReviewRulesAdminInternal,
    openLaborNormsAdmin: openLaborNormsAdminInternal,
    openRepairByIds,
    returnFromRepairPage,
  } = appNavigation;
  const repairDerivedViewModel = useRepairDerivedViewModel({
    selectedDocumentId,
    selectedFile,
    userRole: user?.role,
    selectedRepair,
    reviewQueue,
    summary,
    dataQuality,
    dataQualityDetails,
    formatMoney,
  });
  const {
    selectedReviewItem,
    selectedRepairDocument,
    selectedRepairDocumentPayload,
    selectedRepairDocumentConfidenceMap,
    selectedRepairDocumentExtractedFields,
    selectedRepairDocumentOcrServiceName,
    selectedRepairDocumentWorks,
    selectedRepairDocumentParts,
    selectedRepairUnresolvedChecks,
    selectedRepairAwaitingOcr,
    selectedRepairHasBlockingFindings,
    selectedRepairReportSections,
    selectedRepairDocumentManualReviewReasons,
    repairVisualBars,
    repairVisualMax,
    qualityVisualBars,
    qualityVisualMax,
    attentionVisualBars,
    attentionVisualMax,
    topAttentionServices,
    reviewRequiredFieldComparisons,
    selectedRepairDocumentFieldSnapshots,
    reviewMissingRequiredFields,
    selectedRepairComparisonAttentionCount,
    reviewReadyFieldsCount,
    canConfirmSelectedReview,
    uploadMissingRequirements,
    canLinkVehicleFromSelectedDocument,
    canCreateVehicleFromSelectedDocument,
  } = repairDerivedViewModel;
  const repairEditingWorkflow = useRepairEditingWorkflow({
    token,
    userRole: user?.role,
    selectedRepair,
    refreshWorkspace,
    setSelectedRepair,
    setSelectedDocumentId,
    setActiveWorkspaceTab,
    setErrorMessage,
    setSuccessMessage,
  });
  const {
    repairDraft,
    setRepairDraft,
    isEditingRepair,
    saveRepairLoading,
    repairArchiveLoading,
    repairDeleteLoading,
    startRepairEdit,
    cancelRepairEdit,
    updateRepairDraftField,
    updateWorkDraft,
    updatePartDraft,
    addWorkDraft,
    addPartDraft,
    removeWorkDraft,
    removePartDraft,
    handleSaveRepair,
    handleArchiveRepair,
    handleDeleteRepair,
    syncRepairDraftFromRepair,
    resetRepairEditingState,
  } = repairEditingWorkflow;
  isEditingRepairRef.current = isEditingRepair;
  syncRepairDraftFromRepairRef.current = syncRepairDraftFromRepair;
  const repairReviewWorkflow = useRepairReviewWorkflow({
    token,
    userRole: user?.role,
    selectedRepair,
    selectedRepairDocument,
    selectedReviewItem,
    selectedDocumentId,
    selectedRepairDocumentOcrServiceName,
    selectedRepairDocumentExtractedFields,
    defaultReviewServiceStatus: user?.role === "admin" ? "confirmed" : "preliminary",
    isEditingRepair,
    loadServices,
    refreshWorkspace,
    openRepairByIds,
    setSelectedRepair,
    setRepairDraft: syncRepairDraftFromRepair,
    setErrorMessage,
    setSuccessMessage,
  });
  const {
    reviewActionLoading,
    reviewActionComment,
    setReviewActionComment,
    reviewFieldSaving,
    reviewVehicleSearch,
    setReviewVehicleSearch,
    reviewVehicleSearchLoading,
    reviewVehicleSearchResults,
    reviewVehicleLinkingId,
    reviewServiceAssigning,
    reviewServiceSaving,
    reviewServiceName,
    setReviewServiceName,
    reviewServiceForm,
    setReviewServiceForm,
    showReviewServiceEditor,
    setShowReviewServiceEditor,
    reviewFieldDraft,
    showReviewFieldEditor,
    setShowReviewFieldEditor,
    reviewDocumentPreviewUrl,
    reviewDocumentPreviewLoading,
    reviewDocumentPreviewKind,
    handleReviewAction,
    assignReviewService,
    handleAssignReviewService,
    handleCreateReviewService,
    handleSearchReviewVehicles,
    handleLinkReviewVehicle,
    updateReviewFieldDraft,
    fillReviewFieldDraftFromOcr,
    handleSaveReviewFields,
    resetReviewWorkflowState,
  } = repairReviewWorkflow;
  const repairWorkspaceActions = useRepairWorkspaceActions({
    token,
    userRole: user?.role,
    selectedRepairId: selectedRepair?.id ?? null,
    selectedDocumentId,
    documentVehicleForm,
    checkComments,
    setCheckComments,
    setServiceQuery,
    setErrorMessage,
    setSuccessMessage,
    refreshWorkspace,
    openRepairByIds,
    openServicesAdmin: () => {
      openAdminTab("services");
    },
    loadServices,
    editService,
    openRepairOverviewTab: () => {
      handleRepairTabChange("overview");
    },
    startRepairEdit,
    cancelRepairEdit,
    setSelectedRepairFromApi: setSelectedRepair,
  });
  const {
    repairExportLoading,
    documentVehicleSaving,
    checkActionLoadingId,
    openQualityRepair,
    openQualityService,
    handleExportRepair,
    handleOpenRepair,
    handleCheckResolution,
    handleCreateVehicleFromDocument,
    handleEditService,
    handleStartRepairEdit,
    handleCancelRepairEdit,
  } = repairWorkspaceActions;
  const repairDocumentsWorkflow = useRepairDocumentsWorkflow({
    token,
    selectedRepair,
    selectedDocumentId,
    refreshWorkspace,
    openRepairByIds,
    setErrorMessage,
    setSuccessMessage,
  });
  const {
    attachDocumentLoading,
    documentOpenLoadingId,
    primaryDocumentLoadingId,
    documentComparisonLoadingId,
    documentComparisonReviewLoading,
    attachedDocumentKind,
    setAttachedDocumentKind,
    attachedDocumentNotes,
    setAttachedDocumentNotes,
    attachedDocumentFile,
    setAttachedDocumentFile,
    documentComparison,
    setDocumentComparison,
    documentComparisonComment,
    setDocumentComparisonComment,
    handleOpenDocumentFile,
    handleAttachDocumentToRepair,
    handleSetPrimaryDocument,
    handleCompareWithPrimary,
    handleReviewDocumentComparison,
    resetRepairDocumentsWorkflowState,
  } = repairDocumentsWorkflow;
  resetRepairDocumentsWorkflowStateRef.current = resetRepairDocumentsWorkflowState;
  const workspaceLifecycleAdapters = buildWorkspaceLifecycleAdapters({
    setUser,
    setSummary,
    setDataQuality,
    setDataQualityDetails,
    setVehicles,
    setDocuments,
    setReviewQueue,
    setReviewQueueCounts,
    setSelectedDocumentId,
    setSelectedRepair,
    setLastUploadedDocument,
    setErrorMessage,
    applyBootstrapVehicleList,
    applyBootstrapUsers,
    applyBootstrapLaborNorms,
    applyBootstrapServices,
    applyBootstrapReviewRules,
    applyBootstrapOcrAdmin,
    setShowTechAdminTab,
    setShowPasswordChange,
    setActiveTechAdminTab,
    setActiveQualityTab,
    resetFleetState,
    resetOperationsState,
    resetLaborNormsState,
    resetReviewRulesState,
    resetReviewWorkflowState,
    resetRepairDocumentsWorkflowState,
    resetRepairEditingState,
    resetDocumentsWorkspaceState,
    resetUsersState,
    resetServicesState,
    resetOcrAdminState,
    resetBackupsState,
    resetHistoricalImportsState,
    setDocumentVehicleForm,
    createEmptyDocumentVehicleForm,
  });
  const workspaceDataLifecycle = useWorkspaceDataLifecycle({
    token,
    selectedReviewCategory,
    laborNormQuery,
    laborNormScope,
    laborNormCategory,
    selectedDocumentId,
    documents,
    reviewQueue,
    selectedRepair,
    isEditingRepair,
    lastUploadedDocument,
    invalidateSession,
    loadRepairDetail,
    workspaceState: workspaceLifecycleAdapters.workspaceState,
    resetters: workspaceLifecycleAdapters.resetters,
  });
  const { bootLoading, loadWorkspace: loadWorkspaceInternal } = workspaceDataLifecycle;
  openRepairByIdsRef.current = openRepairByIds;
  openTechAdminRef.current = openTechAdminInternal;
  openReviewRulesAdminRef.current = openReviewRulesAdminInternal;
  openLaborNormsAdminRef.current = openLaborNormsAdminInternal;
  loadWorkspaceRef.current = loadWorkspaceInternal;
  const repairHistoryFilters = useRepairHistoryFilters({
    selectedRepair,
    historyFilter,
    historySearch,
    formatDocumentKind,
  });
  const { filteredRepairHistory, filteredDocumentHistory } = repairHistoryFilters;

  useRepairPresentationState({
    selectedDocumentId,
    selectedRepairId: selectedRepair?.id ?? null,
    selectedRepairServiceName: selectedRepair?.service?.name,
    selectedRepairDocumentPayload,
    selectedRepairDocumentPlateNumber: selectedRepairDocumentExtractedFields?.plate_number,
    selectedRepairDocumentVin: selectedRepairDocumentExtractedFields?.vin,
    selectedRepairDocumentOcrServiceName,
    setDocumentVehicleForm,
    setShowRepairOverviewDetails,
  });

  const workspaceMainViewProps = buildWorkspaceMainViewProps({
    rootState: appRootState,
    authSession,
    documentsWorkspace,
    employeesAdmin,
    servicesAdmin,
    reviewRulesAdmin,
    laborNormsAdmin,
    ocrAdmin,
    historicalImportsAdmin,
    operationsWorkspace: workspaceOperations,
    backupsAdmin,
    fleetWorkspace,
    navigation: appNavigation,
    repairLoading,
    repairDerivedViewModel,
    repairEditingWorkflow,
    repairReviewWorkflow,
    repairWorkspaceActions,
    repairDocumentsWorkflow,
    repairHistoryFilters,
    workspaceDataLifecycle,
  });

  if (!token) {
    return (
      <AuthLandingView
        {...buildAuthLandingProps({
          showPasswordRecoveryRequest,
          loginValue,
          passwordValue,
          loginLoading,
          recoveryEmailValue,
          recoveryTokenValue,
          recoveryNewPasswordValue,
          passwordRecoveryLoading,
          errorMessage,
          successMessage,
          handleLogin,
          setLoginValue,
          setPasswordValue,
          openPasswordRecovery,
          setRecoveryEmailValue,
          handleRequestPasswordRecovery,
          setRecoveryTokenValue,
          setRecoveryNewPasswordValue,
          handleConfirmPasswordRecovery,
          handleBackToLogin,
        })}
      />
    );
  }

  return (
    <WorkspaceMainView {...workspaceMainViewProps} />
  );
}
