import { useRef, useState } from "react";
import {
  buildUserPayload,
} from "./shared/adminPayloadBuilders";
import { MenuItem } from "@mui/material";
import { AuthLandingView } from "./components/AuthLandingView";
import { WorkspaceMainView } from "./components/WorkspaceMainView";
import { useAppNavigation } from "./hooks/useAppNavigation";
import { useAuthSession } from "./hooks/useAuthSession";
import { useBackupsAdmin } from "./hooks/useBackupsAdmin";
import { useDocumentsWorkspace } from "./hooks/useDocumentsWorkspace";
import { useEmployeesAdmin } from "./hooks/useEmployeesAdmin";
import { useLaborNormsAdmin } from "./hooks/useLaborNormsAdmin";
import { useOcrAdmin } from "./hooks/useOcrAdmin";
import { useReviewRulesAdmin } from "./hooks/useReviewRulesAdmin";
import { useRepairDerivedViewModel } from "./hooks/useRepairDerivedViewModel";
import { useRepairDetailLoader } from "./hooks/useRepairDetailLoader";
import { useRepairDocumentsWorkflow } from "./hooks/useRepairDocumentsWorkflow";
import { useRepairEditingWorkflow } from "./hooks/useRepairEditingWorkflow";
import { useRepairHistoryFilters } from "./hooks/useRepairHistoryFilters";
import { useRepairWorkspaceActions } from "./hooks/useRepairWorkspaceActions";
import { useFleetWorkspace } from "./hooks/useFleetWorkspace";
import { useHistoricalImportsAdmin } from "./hooks/useHistoricalImportsAdmin";
import { useRepairReviewWorkflow } from "./hooks/useRepairReviewWorkflow";
import { useRepairPresentationState } from "./hooks/useRepairPresentationState";
import { useServicesAdmin } from "./hooks/useServicesAdmin";
import { useWorkspaceDataLifecycle } from "./hooks/useWorkspaceDataLifecycle";
import { useWorkspaceOperations } from "./hooks/useWorkspaceOperations";
import {
  formatQualityVehicle,
  formatVehicle,
  inferVehicleTypeFromIdentifiers,
  isAssignmentActive,
  isPlaceholderVehicle,
} from "./shared/fleetDocumentHelpers";
import {
  buildDashboardVisualBarWidth,
} from "./shared/dashboardVisuals";
import { type AdminTab, type AppRoute, type RepairTab, type TechAdminTab, type WorkspaceTab } from "./shared/appRoute";
import { buildAuthLandingProps } from "./shared/buildAuthLandingProps";
import { type HistoryDetailFormatters } from "./shared/historyDetails";
import { buildWorkspaceContentProps } from "./shared/buildWorkspaceContentProps";
import {
  buildDataQualityProps,
  buildImportConflictDialogProps,
  buildWorkspaceChromeProps,
} from "./shared/buildWorkspaceShellProps";
import {
  buildCheckPayloadDetails,
  formatOcrLineUnit,
  formatWorkLaborNormMeta,
  getCheckLinkedRepairId,
  readCheckResolutionMeta,
  readComparisonReviewMeta,
  readNumberValue,
  readStringValue,
} from "./shared/repairReportHelpers";
import {
  checkSeverityColor,
  documentHasActiveImportJob,
  executiveRiskColor,
  formatAuditEntityLabel,
  formatCatalogCodeLabel,
  formatCompactNumber,
  formatConfidence,
  formatConfidenceLabel,
  formatDateTime,
  formatDateValue,
  formatDocumentKind,
  formatDocumentStatusLabel,
  formatExecutiveRiskLabel,
  formatFileSize,
  formatHistoryActionLabel,
  formatHours,
  formatJsonPretty,
  formatLaborNormApplicability,
  formatManualReviewReasons,
  formatMoney,
  formatOcrFieldLabel,
  formatOcrLearningStatusLabel,
  formatOcrProfileMeta,
  formatOcrProfileName,
  formatOcrSignalTypeLabel,
  formatRepairStatus,
  formatReviewBucketLabel,
  formatReviewPriority,
  formatReviewRuleTypeLabel,
  formatSourceTypeLabel,
  formatStatus,
  formatUserRoleLabel,
  formatValueParserLabel,
  formatVehicleStatusLabel,
  formatVehicleTypeLabel,
  getConfidenceColor,
  importJobStatusColor,
  isDocumentAwaitingOcr,
  readOcrProfileMeta,
  reviewPriorityColor,
  statusColor,
  vehicleStatusColor,
} from "./shared/displayFormatters";
import {
  createEmptyDocumentVehicleForm,
  createEmptyUserAssignmentForm,
  createEmptyUserForm,
  createServiceFormFromItem,
  createUserFormFromItem,
} from "./shared/formStateFactories";
import {
  adminTabDescriptions,
  documentKindOptions,
  historyFilters,
  qualityCards,
  repairTabDescriptions,
  reviewQueueFilters,
  rootDocumentKindOptions,
  summaryCards,
  techAdminTabDescriptions,
  VEHICLES_FULL_LIST_LIMIT,
  workspaceTabDescriptions,
  workspaceTabReturnLabels,
} from "./shared/appUiConfig";
import type { RepairDetail, RepairDocumentHistoryEntry, RepairHistoryEntry } from "./shared/repairDetailTypes";
import type { HistoryFilter, QualityDetailTab } from "./shared/workspaceViewTypes";
import {
  buildAuditLogQueryString,
  buildServiceQueryString,
  buildUsersQueryString,
} from "./shared/queryBuilders";
import {
  getReviewComparisonColor,
  getReviewComparisonLabel,
  resolveRepairDocumentId,
  type ReviewComparisonStatus,
} from "./shared/repairUiHelpers";
import type {
  HistoricalRepairImportResponse,
  HistoricalWorkReferenceItem,
  HistoricalWorkReferenceResponse,
  ImportConflictItem,
  ImportConflictResolveResponse,
  ImportConflictsResponse,
  ImportJobItem,
  ImportJobsResponse,
} from "./shared/importAdminTypes";
import type {
  DashboardDataQuality,
  DashboardDataQualityDetails,
  DashboardSummary,
  DocumentItem,
  DocumentKind,
  DocumentStatus,
  GlobalSearchResponse,
  ReviewQueueCategory,
  ReviewQueueItem,
  ReviewQueueResponse,
  ServiceStatus,
  ServicesResponse,
  User,
  UserAssignment,
  UserItem,
  UserRole,
  UsersResponse,
  Vehicle,
} from "./shared/workspaceBootstrapTypes";
import type {
  DocumentVehicleFormState,
  ReviewRepairFieldsDraft,
  ServiceFormState,
  UploadFormState,
  UserAssignmentFormState,
  UserFormState,
} from "./shared/workspaceFormTypes";

const emptyUploadForm = (): UploadFormState => ({
  vehicleId: "",
  documentKind: "order",
  repairDate: "",
  mileage: "",
  orderNumber: "",
  reason: "",
  employeeComment: "",
  notes: "",
});

// Predeploy marker: uploaded: "В очереди OCR"


const historyDetailFormatters: HistoryDetailFormatters = {
  formatStatus,
  formatRepairStatus,
  formatDocumentStatusLabel,
  formatDocumentKind,
  formatMoney,
  formatDateValue,
  formatJsonPretty,
  readComparisonReviewMeta,
};

export default function App() {
  const [user, setUser] = useState<User | null>(null);
  const [activeWorkspaceTab, setActiveWorkspaceTab] = useState<WorkspaceTab>("documents");
  const [activeAdminTab, setActiveAdminTab] = useState<AdminTab>("services");
  const [activeTechAdminTab, setActiveTechAdminTab] = useState<TechAdminTab>("learning");
  const [activeRepairTab, setActiveRepairTab] = useState<RepairTab>("overview");
  const [activeQualityTab, setActiveQualityTab] = useState<QualityDetailTab>("documents");
  const [showQualityDialog, setShowQualityDialog] = useState(false);
  const [showTechAdminTab, setShowTechAdminTab] = useState(false);
  const [summary, setSummary] = useState<DashboardSummary | null>(null);
  const [dataQuality, setDataQuality] = useState<DashboardDataQuality | null>(null);
  const [dataQualityDetails, setDataQualityDetails] = useState<DashboardDataQualityDetails | null>(null);
  const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [documents, setDocuments] = useState<DocumentItem[]>([]);
  const [reviewQueue, setReviewQueue] = useState<ReviewQueueItem[]>([]);
  const [reviewQueueCounts, setReviewQueueCounts] = useState<Record<ReviewQueueCategory, number>>({
    all: 0,
    suspicious: 0,
    ocr_error: 0,
    partial_recognition: 0,
    employee_confirmation: 0,
    manual_review: 0,
  });
  const [selectedReviewCategory, setSelectedReviewCategory] = useState<ReviewQueueCategory>("all");
  const [selectedDocumentId, setSelectedDocumentId] = useState<number | null>(null);
  const [selectedRepair, setSelectedRepair] = useState<RepairDetail | null>(null);
  const [documentVehicleForm, setDocumentVehicleForm] = useState<DocumentVehicleFormState>(createEmptyDocumentVehicleForm);
  const attachedFileInputRef = useRef<HTMLInputElement | null>(null);
  const [checkComments, setCheckComments] = useState<Record<number, string>>({});
  const [historyFilter, setHistoryFilter] = useState<HistoryFilter>("all");
  const [historySearch, setHistorySearch] = useState("");
  const [showRepairOverviewDetails, setShowRepairOverviewDetails] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const isEditingRepairRef = useRef(false);
  const syncRepairDraftFromRepairRef = useRef<(repair: RepairDetail) => void>(() => {});
  const resetRepairDocumentsWorkflowStateRef = useRef<() => void>(() => {});

  async function openRepairByIdsFromDocuments(documentId: number | null, repairId: number) {
    await openRepairByIds(documentId, repairId);
  }

  const {
    token,
    showPasswordChange,
    setShowPasswordChange,
    showPasswordRecoveryRequest,
    loginValue,
    setLoginValue,
    passwordValue,
    setPasswordValue,
    currentPasswordValue,
    setCurrentPasswordValue,
    newPasswordValue,
    setNewPasswordValue,
    recoveryEmailValue,
    setRecoveryEmailValue,
    recoveryTokenValue,
    setRecoveryTokenValue,
    recoveryNewPasswordValue,
    setRecoveryNewPasswordValue,
    loginLoading,
    passwordChangeLoading,
    passwordRecoveryLoading,
    invalidateSession,
    handleLogin,
    handleChangePassword,
    handleRequestPasswordRecovery,
    handleConfirmPasswordRecovery,
    openPasswordRecovery,
    handleBackToLogin,
    cancelPasswordChange,
    handleLogout,
  } = useAuthSession({
    setErrorMessage,
    setSuccessMessage,
    onLogoutAppReset: () => {
      setActiveWorkspaceTab("documents");
      setActiveAdminTab("services");
      setActiveTechAdminTab("learning");
      setActiveRepairTab("overview");
      setShowTechAdminTab(false);
      setLastUploadedDocument(null);
      resetRepairDocumentsWorkflowState();
    },
  });
  const {
    uploadForm,
    selectedFile,
    lastUploadedDocument,
    setLastUploadedDocument,
    uploadFileInputRef,
    uploadLoading,
    reprocessLoading,
    batchReprocessLoading,
    batchReprocessLimit,
    setBatchReprocessLimit,
    batchReprocessStatusFilter,
    setBatchReprocessStatusFilter,
    batchReprocessPrimaryOnly,
    setBatchReprocessPrimaryOnly,
    documentArchiveLoadingId,
    handleUpload,
    updateUploadFormField,
    handleUploadFileSelect,
    handleReprocessDocumentById,
    handleReprocessDocument,
    handleBatchReprocessDocuments,
    handleArchiveDocument,
    resetDocumentsWorkspaceState,
  } = useDocumentsWorkspace({
    token,
    userRole: user?.role,
    emptyUploadForm,
    setErrorMessage,
    setSuccessMessage,
    refreshWorkspace,
    openRepairByIds: openRepairByIdsFromDocuments,
    selectedDocumentId,
    selectedRepairId: selectedRepair?.id ?? null,
    formatDocumentStatusLabel,
  });
  const {
    usersList,
    usersTotal,
    userLoading,
    userSaving,
    userSearch,
    setUserSearch,
    showUserEditor,
    setShowUserEditor,
    userForm,
    selectedManagedUserId,
    setSelectedManagedUserId,
    selectedManagedUser,
    adminResetPasswordValue,
    setAdminResetPasswordValue,
    userVehicleSearch,
    setUserVehicleSearch,
    userVehicleSearchLoading,
    userVehicleSearchResults,
    userAssignmentForm,
    userAssignmentSaving,
    applyBootstrapUsers,
    resetUserEditor,
    editUser,
    updateUserFormField,
    updateUserAssignmentFormField,
    handleUserSearch,
    resetUsersSearch,
    handleSaveUser,
    handleSearchVehiclesForAssignment,
    handleCreateUserAssignment,
    handleAdminResetUserPassword,
    handleCloseUserAssignment,
    resetUsersState,
  } = useEmployeesAdmin({
    token,
    userRole: user?.role,
    setErrorMessage,
    setSuccessMessage,
  });
  const {
    services,
    serviceCities,
    serviceQuery,
    setServiceQuery,
    serviceCityFilter,
    setServiceCityFilter,
    serviceLoading,
    serviceSaving,
    serviceForm,
    showServiceEditor,
    setShowServiceEditor,
    showServiceListDialog,
    setShowServiceListDialog,
    applyBootstrapServices,
    loadServices,
    updateServiceFormField,
    editService,
    resetServiceEditor,
    handleServiceSearch,
    resetServicesFilters,
    handleSaveService,
    resetServicesState,
  } = useServicesAdmin({
    token,
    userRole: user?.role,
    setErrorMessage,
    setSuccessMessage,
  });
  const {
    showReviewRuleEditor,
    setShowReviewRuleEditor,
    showReviewRuleListDialog,
    setShowReviewRuleListDialog,
    reviewRules,
    reviewRuleTypes,
    reviewRuleSaving,
    reviewRuleForm,
    applyBootstrapReviewRules,
    updateReviewRuleFormField,
    editReviewRule,
    resetReviewRuleEditor,
    handleSaveReviewRule,
    resetReviewRulesState,
  } = useReviewRulesAdmin({
    token,
    userRole: user?.role,
    setErrorMessage,
    setSuccessMessage,
    openReviewRulesAdmin,
  });
  const {
    showLaborNormCatalogEditor,
    setShowLaborNormCatalogEditor,
    showLaborNormImport,
    setShowLaborNormImport,
    showLaborNormEntryEditor,
    setShowLaborNormEntryEditor,
    showLaborNormListDialog,
    setShowLaborNormListDialog,
    laborNorms,
    laborNormCatalogs,
    laborNormTotal,
    laborNormScopes,
    laborNormCategories,
    laborNormSourceFiles,
    laborNormQuery,
    setLaborNormQuery,
    laborNormScope,
    setLaborNormScope,
    laborNormCategory,
    setLaborNormCategory,
    laborNormLoading,
    laborNormImportLoading,
    laborNormFile,
    setLaborNormFile,
    laborNormImportScope,
    laborNormImportBrandFamily,
    setLaborNormImportBrandFamily,
    laborNormImportCatalogName,
    setLaborNormImportCatalogName,
    laborNormCatalogSaving,
    laborNormEntrySaving,
    editingLaborNormCatalogId,
    laborNormCatalogForm,
    laborNormEntryForm,
    applyBootstrapLaborNorms,
    updateLaborNormCatalogFormField,
    handleLaborNormSearch,
    resetLaborNormFilters,
    handleLaborNormImport,
    editLaborNormCatalog,
    resetLaborNormCatalogEditor,
    selectCatalogScope,
    handleSaveLaborNormCatalog,
    updateLaborNormEntryFormField,
    editLaborNormItem,
    resetLaborNormEntryEditor,
    handleSaveLaborNormEntry,
    handleArchiveLaborNormItem,
    resetLaborNormsState,
  } = useLaborNormsAdmin({
    token,
    userRole: user?.role,
    setErrorMessage,
    setSuccessMessage,
    openLaborNormsAdmin,
  });
  const {
    ocrRules,
    ocrRuleProfiles,
    ocrRuleTargetFields,
    ocrRuleProfileFilter,
    setOcrRuleProfileFilter,
    ocrRuleSaving,
    ocrRuleForm,
    ocrProfileMatchers,
    ocrProfileMatcherProfiles,
    ocrProfileMatcherProfileFilter,
    setOcrProfileMatcherProfileFilter,
    ocrProfileMatcherSaving,
    ocrProfileMatcherForm,
    ocrLearningSignals,
    ocrLearningSummaries,
    ocrLearningStatuses,
    ocrLearningTargetFields,
    ocrLearningProfileScopes,
    systemStatus,
    ocrLearningStatusFilter,
    setOcrLearningStatusFilter,
    ocrLearningTargetFieldFilter,
    setOcrLearningTargetFieldFilter,
    ocrLearningProfileScopeFilter,
    setOcrLearningProfileScopeFilter,
    showOcrLearningListDialog,
    setShowOcrLearningListDialog,
    ocrLearningLoading,
    ocrLearningUpdateId,
    ocrLearningDraftId,
    applyBootstrapOcrAdmin,
    loadOcrRules,
    loadOcrProfileMatchers,
    loadOcrLearningSignals,
    updateOcrRuleFormField,
    editOcrRule,
    resetOcrRuleEditor,
    handleSaveOcrRule,
    updateOcrProfileMatcherFormField,
    editOcrProfileMatcher,
    resetOcrProfileMatcherEditor,
    handleSaveOcrProfileMatcher,
    handleUpdateOcrLearningSignal,
    handleLoadOcrLearningDraft,
    resetOcrAdminState,
  } = useOcrAdmin({
    token,
    userRole: user?.role,
    setErrorMessage,
    setSuccessMessage,
    openTechAdmin,
  });
  const {
    historicalImportLoading,
    historicalImportFile,
    setHistoricalImportFile,
    historicalImportLimit,
    setHistoricalImportLimit,
    historicalImportResult,
    historicalImportJobs,
    historicalImportJobsLoading,
    historicalWorkReference,
    historicalWorkReferenceLoading,
    historicalWorkReferenceTotal,
    historicalWorkReferenceQuery,
    setHistoricalWorkReferenceQuery,
    historicalWorkReferenceMinSamples,
    setHistoricalWorkReferenceMinSamples,
    importConflicts,
    importConflictsLoading,
    selectedImportConflict,
    showImportConflictDialog,
    importConflictLoading,
    importConflictSaving,
    importConflictComment,
    setImportConflictComment,
    setShowImportConflictDialog,
    loadHistoricalWorkReference,
    refreshHistoricalImportsJournal,
    openImportConflict,
    handleHistoricalRepairImport,
    handleResolveImportConflict,
    resetHistoricalImportsState,
  } = useHistoricalImportsAdmin({
    token,
    userRole: user?.role,
    activeWorkspaceTab,
    activeAdminTab,
    setErrorMessage,
    setSuccessMessage,
    refreshWorkspace,
  });
  const {
    globalSearchQuery,
    setGlobalSearchQuery,
    globalSearchLoading,
    globalSearchResult,
    handleGlobalSearchSubmit,
    resetGlobalSearch,
    auditLogItems,
    auditLogLoading,
    auditLogTotal,
    auditEntityTypes,
    auditActionTypes,
    auditSearchQuery,
    setAuditSearchQuery,
    auditEntityTypeFilter,
    setAuditEntityTypeFilter,
    auditActionTypeFilter,
    setAuditActionTypeFilter,
    auditUserIdFilter,
    setAuditUserIdFilter,
    auditDateFrom,
    setAuditDateFrom,
    auditDateTo,
    setAuditDateTo,
    loadAuditLog,
    resetAudit,
    resetOperationsState,
  } = useWorkspaceOperations({
    activeWorkspaceTab,
    token,
    onError: setErrorMessage,
  });
  const {
    backups,
    backupsLoading,
    backupActionLoading,
    backupRestoreDialogOpen,
    backupRestoreTarget,
    backupRestoreConfirmValue,
    setBackupRestoreConfirmValue,
    loadBackups,
    openBackupRestoreDialog,
    closeBackupRestoreDialog,
    handleCreateBackup,
    handleDownloadBackup,
    handleRestoreBackup,
    resetBackupsState,
  } = useBackupsAdmin({
    token,
    userRole: user?.role,
    activeWorkspaceTab,
    activeAdminTab,
    setErrorMessage,
    setSuccessMessage,
  });
  const {
    fleetVehicles,
    fleetVehiclesTotal,
    fleetLoading,
    fleetQuery,
    setFleetQuery,
    fleetVehicleTypeFilter,
    setFleetVehicleTypeFilter,
    fleetStatusFilter,
    setFleetStatusFilter,
    selectedFleetVehicleId,
    setSelectedFleetVehicleId,
    selectedFleetVehicle,
    selectedFleetVehicleLoading,
    fleetViewMode,
    setFleetViewMode,
    vehicleSaving,
    vehicleExportLoading,
    loadFleetVehicles,
    applyBootstrapVehicleList,
    openFleetVehicleCard,
    returnToFleetList,
    openFleetVehicleById,
    handleUpdateVehicle,
    handleExportVehicle,
    resetFleetState,
  } = useFleetWorkspace({
    token,
    activeWorkspaceTab,
    vehiclesFullListLimit: VEHICLES_FULL_LIST_LIMIT,
    setErrorMessage,
    setSuccessMessage,
  });
  const { repairLoading, loadRepairDetail } = useRepairDetailLoader<RepairDetail, DocumentItem>({
    setErrorMessage,
    setSelectedRepair: (repair) => {
      setSelectedRepair(repair);
    },
    setSelectedDocumentId,
    setLastUploadedDocument,
    setCheckComments,
    setHistoryFilter,
    setHistorySearch,
    isEditingRepairRef,
    syncRepairDraftFromRepairRef,
    resetRepairDocumentsWorkflowStateRef,
  });
  const appNavigation = useAppNavigation({
    userRole: user?.role,
    token,
    activeWorkspaceTab,
    setActiveWorkspaceTab,
    activeAdminTab,
    setActiveAdminTab,
    activeTechAdminTab,
    setActiveTechAdminTab,
    activeRepairTab,
    setActiveRepairTab,
    showTechAdminTab,
    setShowTechAdminTab,
    fleetViewMode,
    setFleetViewMode,
    selectedFleetVehicleId,
    setSelectedFleetVehicleId,
    selectedRepairId: selectedRepair?.id ?? null,
    selectedDocumentId,
    setSelectedDocumentId,
    loadRepairDetail,
  });
  const {
    repairHasReturnTarget,
    repairReturnTab,
    updateBrowserRoute,
    handleWorkspaceTabChange,
    handleAdminTabChange,
    handleTechAdminTabChange,
    handleRepairTabChange,
    openAdminTab,
    openTechAdmin: openTechAdminInternal,
    closeTechAdmin,
    openReviewRulesAdmin: openReviewRulesAdminInternal,
    openLaborNormsAdmin: openLaborNormsAdminInternal,
    openRepairByIds,
    returnFromRepairPage,
  } = appNavigation;

  function openTechAdmin(tab: TechAdminTab = "learning") {
    openTechAdminInternal(tab);
  }

  function openReviewRulesAdmin() {
    openReviewRulesAdminInternal();
  }

  function openLaborNormsAdmin() {
    openLaborNormsAdminInternal();
  }

  async function refreshWorkspace() {
    if (token) {
      await loadWorkspace(token);
    }
  }
  const {
    selectedReviewItem,
    selectedRepairDocument,
    selectedRepairDocumentPayload,
    selectedRepairDocumentConfidenceMap,
    selectedRepairDocumentExtractedFields,
    selectedRepairDocumentOcrServiceName,
    selectedRepairDocumentWorks,
    selectedRepairDocumentParts,
    selectedRepairUnresolvedChecks,
    selectedRepairAwaitingOcr,
    selectedRepairHasBlockingFindings,
    selectedRepairReportSections,
    selectedRepairDocumentManualReviewReasons,
    repairVisualBars,
    repairVisualMax,
    qualityVisualBars,
    qualityVisualMax,
    attentionVisualBars,
    attentionVisualMax,
    topAttentionServices,
    reviewRequiredFieldComparisons,
    selectedRepairDocumentFieldSnapshots,
    reviewMissingRequiredFields,
    selectedRepairComparisonAttentionCount,
    reviewReadyFieldsCount,
    canConfirmSelectedReview,
    uploadMissingRequirements,
    canLinkVehicleFromSelectedDocument,
    canCreateVehicleFromSelectedDocument,
  } = useRepairDerivedViewModel({
    selectedDocumentId,
    selectedFile,
    userRole: user?.role,
    selectedRepair,
    reviewQueue,
    summary,
    dataQuality,
    dataQualityDetails,
    formatMoney,
  });
  const {
    repairDraft,
    setRepairDraft,
    isEditingRepair,
    saveRepairLoading,
    repairArchiveLoading,
    repairDeleteLoading,
    startRepairEdit,
    cancelRepairEdit,
    updateRepairDraftField,
    updateWorkDraft,
    updatePartDraft,
    addWorkDraft,
    addPartDraft,
    removeWorkDraft,
    removePartDraft,
    handleSaveRepair,
    handleArchiveRepair,
    handleDeleteRepair,
    syncRepairDraftFromRepair,
    resetRepairEditingState,
  } = useRepairEditingWorkflow({
    token,
    userRole: user?.role,
    selectedRepair,
    refreshWorkspace,
    setSelectedRepair: (repair) => {
      setSelectedRepair(repair as RepairDetail | null);
    },
    setSelectedDocumentId,
    setActiveWorkspaceTab,
    setErrorMessage,
    setSuccessMessage,
  });
  isEditingRepairRef.current = isEditingRepair;
  syncRepairDraftFromRepairRef.current = syncRepairDraftFromRepair;
  const {
    reviewActionLoading,
    reviewActionComment,
    setReviewActionComment,
    reviewFieldSaving,
    reviewVehicleSearch,
    setReviewVehicleSearch,
    reviewVehicleSearchLoading,
    reviewVehicleSearchResults,
    reviewVehicleLinkingId,
    reviewServiceAssigning,
    reviewServiceSaving,
    reviewServiceName,
    setReviewServiceName,
    reviewServiceForm,
    setReviewServiceForm,
    showReviewServiceEditor,
    setShowReviewServiceEditor,
    reviewFieldDraft,
    showReviewFieldEditor,
    setShowReviewFieldEditor,
    reviewDocumentPreviewUrl,
    reviewDocumentPreviewLoading,
    reviewDocumentPreviewKind,
    handleReviewAction,
    assignReviewService,
    handleAssignReviewService,
    handleCreateReviewService,
    handleSearchReviewVehicles,
    handleLinkReviewVehicle,
    updateReviewFieldDraft,
    fillReviewFieldDraftFromOcr,
    handleSaveReviewFields,
    resetReviewWorkflowState,
  } = useRepairReviewWorkflow({
    token,
    userRole: user?.role,
    selectedRepair,
    selectedRepairDocument,
    selectedReviewItem,
    selectedDocumentId,
    selectedRepairDocumentOcrServiceName,
    selectedRepairDocumentExtractedFields,
    defaultReviewServiceStatus: user?.role === "admin" ? "confirmed" : "preliminary",
    isEditingRepair,
    loadServices,
    refreshWorkspace,
    openRepairByIds,
    setSelectedRepair: (repair) => {
      setSelectedRepair(repair as RepairDetail);
    },
    setRepairDraft: (repair) => {
      syncRepairDraftFromRepair(repair);
    },
    setErrorMessage,
    setSuccessMessage,
  });
  const {
    repairExportLoading,
    documentVehicleSaving,
    checkActionLoadingId,
    openQualityRepair,
    openQualityService,
    handleExportRepair,
    handleOpenRepair,
    handleCheckResolution,
    handleCreateVehicleFromDocument,
    handleEditService,
    handleStartRepairEdit,
    handleCancelRepairEdit,
  } = useRepairWorkspaceActions({
    token,
    userRole: user?.role,
    selectedRepairId: selectedRepair?.id ?? null,
    selectedDocumentId,
    documentVehicleForm,
    checkComments,
    setCheckComments,
    setServiceQuery,
    setErrorMessage,
    setSuccessMessage,
    refreshWorkspace,
    openRepairByIds,
    openServicesAdmin: () => {
      openAdminTab("services");
    },
    loadServices,
    editService,
    openRepairOverviewTab: () => {
      handleRepairTabChange("overview");
    },
    startRepairEdit,
    cancelRepairEdit,
    setSelectedRepairFromApi: (repair) => {
      setSelectedRepair(repair as RepairDetail);
    },
  });
  const {
    attachDocumentLoading,
    documentOpenLoadingId,
    primaryDocumentLoadingId,
    documentComparisonLoadingId,
    documentComparisonReviewLoading,
    attachedDocumentKind,
    setAttachedDocumentKind,
    attachedDocumentNotes,
    setAttachedDocumentNotes,
    attachedDocumentFile,
    setAttachedDocumentFile,
    documentComparison,
    setDocumentComparison,
    documentComparisonComment,
    setDocumentComparisonComment,
    handleOpenDocumentFile,
    handleAttachDocumentToRepair,
    handleSetPrimaryDocument,
    handleCompareWithPrimary,
    handleReviewDocumentComparison,
    resetRepairDocumentsWorkflowState,
  } = useRepairDocumentsWorkflow({
    token,
    selectedRepair,
    selectedDocumentId,
    refreshWorkspace,
    openRepairByIds,
    setErrorMessage,
    setSuccessMessage,
  });
  resetRepairDocumentsWorkflowStateRef.current = resetRepairDocumentsWorkflowState;
  const { bootLoading, loadWorkspace: loadWorkspaceInternal } = useWorkspaceDataLifecycle({
    token,
    selectedReviewCategory,
    laborNormQuery,
    laborNormScope,
    laborNormCategory,
    selectedDocumentId,
    documents,
    reviewQueue,
    selectedRepair,
    isEditingRepair,
    lastUploadedDocument,
    invalidateSession,
    loadRepairDetail,
    workspaceState: {
      setUser,
      setSummary,
      setDataQuality,
      setDataQualityDetails,
      setVehicles,
      setDocuments,
      setReviewQueue,
      setReviewQueueCounts,
      setSelectedDocumentId,
      clearSelectedRepair: () => {
        setSelectedRepair(null);
      },
      setLastUploadedDocument,
      setErrorMessage,
      applyBootstrapVehicleList,
      applyBootstrapUsers,
      applyBootstrapLaborNorms,
      applyBootstrapServices,
      applyBootstrapReviewRules,
      applyBootstrapOcrAdmin,
    },
    resetters: {
      setShowTechAdminTab,
      setShowPasswordChange,
      setActiveTechAdminTab,
      setActiveQualityTab,
      resetFleetState,
      resetOperationsState,
      resetLaborNormsState,
      resetReviewRulesState,
      resetReviewWorkflowState,
      resetRepairDocumentsWorkflowState,
      resetRepairEditingState,
      resetDocumentsWorkspaceState,
      resetUsersState,
      resetServicesState,
      resetOcrAdminState,
      resetBackupsState,
      resetHistoricalImportsState,
      setDocumentVehicleFormToEmpty: () => {
        setDocumentVehicleForm(createEmptyDocumentVehicleForm());
      },
    },
  });
  const { filteredRepairHistory, filteredDocumentHistory } = useRepairHistoryFilters({
    selectedRepair,
    historyFilter,
    historySearch,
    formatDocumentKind: (kind) => formatDocumentKind(kind as DocumentKind),
  });

  async function loadWorkspace(
    activeToken: string,
    reviewCategory: ReviewQueueCategory = selectedReviewCategory,
    options?: { silent?: boolean },
  ) {
    await loadWorkspaceInternal(activeToken, reviewCategory, options);
  }

  useRepairPresentationState({
    selectedDocumentId,
    selectedRepairId: selectedRepair?.id ?? null,
    selectedRepairServiceName: selectedRepair?.service?.name,
    selectedRepairDocumentPayload,
    selectedRepairDocumentPlateNumber: selectedRepairDocumentExtractedFields?.plate_number,
    selectedRepairDocumentVin: selectedRepairDocumentExtractedFields?.vin,
    selectedRepairDocumentOcrServiceName,
    setDocumentVehicleForm,
    setShowRepairOverviewDetails,
  });

  if (!token) {
    return (
      <AuthLandingView
        {...buildAuthLandingProps({
          showPasswordRecoveryRequest,
          loginValue,
          passwordValue,
          loginLoading,
          recoveryEmailValue,
          recoveryTokenValue,
          recoveryNewPasswordValue,
          passwordRecoveryLoading,
          errorMessage,
          successMessage,
          handleLogin,
          setLoginValue,
          setPasswordValue,
          openPasswordRecovery,
          setRecoveryEmailValue,
          handleRequestPasswordRecovery,
          setRecoveryTokenValue,
          setRecoveryNewPasswordValue,
          handleConfirmPasswordRecovery,
          handleBackToLogin,
        })}
      />
    );
  }

  return (
    <WorkspaceMainView
      chromeProps={buildWorkspaceChromeProps({
        user,
        showPasswordChange,
        currentPasswordValue,
        newPasswordValue,
        passwordChangeLoading,
        errorMessage,
        successMessage,
        bootLoading,
        activeWorkspaceTab,
        documents,
        selectedRepair,
        showTechAdminTab,
        vehicles,
        workspaceTabDescriptions,
        summary,
        summaryCards,
        setShowPasswordChange,
        setCurrentPasswordValue,
        setNewPasswordValue,
        handleChangePassword,
        cancelPasswordChange,
        handleLogout,
        handleWorkspaceTabChange,
      })}
      dataQualityProps={buildDataQualityProps({
        dataQuality,
        qualityCards,
        repairVisualBars,
        repairVisualMax,
        qualityVisualBars,
        qualityVisualMax,
        attentionVisualBars,
        attentionVisualMax,
        topAttentionServices,
        dataQualityDetails,
        showQualityDialog,
        activeQualityTab,
        userRole: user?.role,
        setShowQualityDialog,
        setActiveQualityTab,
        openQualityRepair,
        openQualityService,
        openImportConflict,
        buildDashboardVisualBarWidth,
        formatConfidence,
        formatMoney,
        formatQualityVehicle,
        statusColor,
        formatDocumentStatusLabel,
        formatRepairStatus,
        formatDateTime,
      })}
      importConflictDialogProps={buildImportConflictDialogProps({
        showImportConflictDialog,
        importConflictLoading,
        importConflictSaving,
        selectedImportConflict,
        importConflictComment,
        setShowImportConflictDialog,
        setImportConflictComment,
        handleResolveImportConflict,
        formatStatus,
        formatDateTime,
        formatJsonPretty,
      })}
      contentProps={buildWorkspaceContentProps({
        userRole: user?.role,
        activeAdminTab,
        activeRepairTab,
        activeTechAdminTab,
        activeWorkspaceTab,
        addPartDraft,
        addWorkDraft,
        adminResetPasswordValue,
        adminTabDescriptions,
        assignReviewService,
        attachDocumentLoading,
        attachedDocumentFile,
        attachedDocumentKind,
        attachedDocumentNotes,
        attachedFileInputRef,
        auditActionTypeFilter,
        auditActionTypes,
        auditDateFrom,
        auditDateTo,
        auditEntityTypeFilter,
        auditEntityTypes,
        auditLogItems,
        auditLogLoading,
        auditLogTotal,
        auditSearchQuery,
        auditUserIdFilter,
        backupActionLoading,
        backupRestoreConfirmValue,
        backupRestoreDialogOpen,
        backupRestoreTarget,
        backups,
        backupsLoading,
        batchReprocessLimit,
        batchReprocessLoading,
        batchReprocessPrimaryOnly,
        batchReprocessStatusFilter,
        buildCheckPayloadDetails,
        canConfirmSelectedReview,
        canCreateVehicleFromSelectedDocument,
        canLinkVehicleFromSelectedDocument,
        checkActionLoadingId,
        checkComments,
        checkSeverityColor,
        closeBackupRestoreDialog,
        closeTechAdmin,
        documentArchiveLoadingId,
        documentComparison,
        documentComparisonComment,
        documentComparisonLoadingId,
        documentComparisonReviewLoading,
        documentHasActiveImportJob,
        documentKindOptions,
        documentOpenLoadingId,
        documentVehicleForm,
        documentVehicleSaving,
        documents,
        editLaborNormCatalog,
        editLaborNormItem,
        editOcrProfileMatcher,
        editOcrRule,
        editReviewRule,
        editUser,
        editingLaborNormCatalogId,
        executiveRiskColor,
        fillReviewFieldDraftFromOcr,
        filteredDocumentHistory,
        filteredRepairHistory,
        fleetLoading,
        fleetQuery,
        fleetStatusFilter,
        fleetVehicleTypeFilter,
        fleetVehicles,
        fleetVehiclesTotal,
        fleetViewMode,
        formatAuditEntityLabel,
        formatCatalogCodeLabel,
        formatCompactNumber,
        formatConfidence,
        formatConfidenceLabel,
        formatDateTime,
        formatDateValue,
        formatDocumentKind,
        formatDocumentStatusLabel,
        formatExecutiveRiskLabel,
        formatFileSize,
        formatHistoryActionLabel,
        formatHours,
        formatLaborNormApplicability,
        formatManualReviewReasons,
        formatMoney,
        formatOcrFieldLabel,
        formatOcrLearningStatusLabel,
        formatOcrLineUnit,
        formatOcrProfileMeta,
        formatOcrProfileName,
        formatOcrSignalTypeLabel,
        formatRepairStatus,
        formatReviewBucketLabel,
        formatReviewPriority,
        formatReviewRuleTypeLabel,
        formatSourceTypeLabel,
        formatStatus,
        formatUserRoleLabel,
        formatValueParserLabel,
        formatVehicle,
        formatVehicleStatusLabel,
        formatVehicleTypeLabel,
        formatWorkLaborNormMeta,
        getCheckLinkedRepairId,
        getConfidenceColor,
        getReviewComparisonColor,
        getReviewComparisonLabel,
        globalSearchLoading,
        globalSearchQuery,
        globalSearchResult,
        handleAdminResetUserPassword,
        handleAdminTabChange,
        handleArchiveDocument,
        handleArchiveLaborNormItem,
        handleArchiveRepair,
        handleAssignReviewService,
        handleAttachDocumentToRepair,
        handleBatchReprocessDocuments,
        handleCancelRepairEdit,
        handleCheckResolution,
        handleCloseUserAssignment,
        handleCompareWithPrimary,
        handleCreateBackup,
        handleCreateReviewService,
        handleCreateUserAssignment,
        handleCreateVehicleFromDocument,
        handleDeleteRepair,
        handleDownloadBackup,
        handleEditService,
        handleExportRepair,
        handleExportVehicle,
        handleGlobalSearchSubmit,
        handleHistoricalRepairImport,
        handleLaborNormImport,
        handleLaborNormSearch,
        handleLinkReviewVehicle,
        handleLoadOcrLearningDraft,
        handleOpenDocumentFile,
        handleOpenRepair,
        handleRepairTabChange,
        handleReprocessDocument,
        handleReprocessDocumentById,
        handleRestoreBackup,
        handleReviewAction,
        handleReviewDocumentComparison,
        handleSaveLaborNormCatalog,
        handleSaveLaborNormEntry,
        handleSaveOcrProfileMatcher,
        handleSaveOcrRule,
        handleSaveRepair,
        handleSaveReviewFields,
        handleSaveReviewRule,
        handleSaveService,
        handleSaveUser,
        handleSearchReviewVehicles,
        handleSearchVehiclesForAssignment,
        handleServiceSearch,
        handleSetPrimaryDocument,
        handleStartRepairEdit,
        handleTechAdminTabChange,
        handleUpdateOcrLearningSignal,
        handleUpdateVehicle,
        handleUpload,
        handleUploadFileSelect,
        handleUserSearch,
        historicalImportFile,
        historicalImportJobs,
        historicalImportJobsLoading,
        historicalImportLimit,
        historicalImportLoading,
        historicalImportResult,
        historicalWorkReference,
        historicalWorkReferenceLoading,
        historicalWorkReferenceMinSamples,
        historicalWorkReferenceQuery,
        historicalWorkReferenceTotal,
        historyDetailFormatters,
        historyFilter,
        historyFilters,
        historySearch,
        importConflicts,
        importConflictsLoading,
        importJobStatusColor,
        isAssignmentActive,
        isDocumentAwaitingOcr,
        isEditingRepair,
        isPlaceholderVehicle,
        laborNormCatalogForm,
        laborNormCatalogSaving,
        laborNormCatalogs,
        laborNormCategories,
        laborNormCategory,
        laborNormEntryForm,
        laborNormEntrySaving,
        laborNormFile,
        laborNormImportBrandFamily,
        laborNormImportCatalogName,
        laborNormImportLoading,
        laborNormImportScope,
        laborNormLoading,
        laborNormQuery,
        laborNormScope,
        laborNormScopes,
        laborNormSourceFiles,
        laborNormTotal,
        laborNorms,
        lastUploadedDocument,
        loadAuditLog,
        loadBackups,
        loadFleetVehicles,
        loadHistoricalWorkReference,
        loadOcrLearningSignals,
        loadOcrProfileMatchers,
        loadOcrRules,
        ocrLearningDraftId,
        ocrLearningLoading,
        ocrLearningProfileScopeFilter,
        ocrLearningProfileScopes,
        ocrLearningSignals,
        ocrLearningStatusFilter,
        ocrLearningStatuses,
        ocrLearningSummaries,
        ocrLearningTargetFieldFilter,
        ocrLearningTargetFields,
        ocrLearningUpdateId,
        ocrProfileMatcherForm,
        ocrProfileMatcherProfileFilter,
        ocrProfileMatcherProfiles,
        ocrProfileMatcherSaving,
        ocrProfileMatchers,
        ocrRuleForm,
        ocrRuleProfileFilter,
        ocrRuleProfiles,
        ocrRuleSaving,
        ocrRuleTargetFields,
        ocrRules,
        openBackupRestoreDialog,
        openFleetVehicleById,
        openFleetVehicleCard,
        openImportConflict,
        openLaborNormsAdmin,
        openRepairByIds,
        openReviewRulesAdmin,
        openTechAdmin,
        primaryDocumentLoadingId,
        readCheckResolutionMeta,
        readNumberValue,
        readStringValue,
        refreshHistoricalImportsJournal,
        removePartDraft,
        removeWorkDraft,
        repairArchiveLoading,
        repairDeleteLoading,
        repairDraft,
        repairExportLoading,
        repairHasReturnTarget,
        repairLoading,
        repairReturnTab,
        repairTabDescriptions,
        reprocessLoading,
        resetAudit,
        resetGlobalSearch,
        resetLaborNormCatalogEditor,
        resetLaborNormEntryEditor,
        resetLaborNormFilters,
        resetOcrProfileMatcherEditor,
        resetOcrRuleEditor,
        resetReviewRuleEditor,
        resetServiceEditor,
        resetServicesFilters,
        resetUserEditor,
        resetUsersSearch,
        returnFromRepairPage,
        returnToFleetList,
        reviewActionComment,
        reviewActionLoading,
        reviewDocumentPreviewKind,
        reviewDocumentPreviewLoading,
        reviewDocumentPreviewUrl,
        reviewFieldDraft,
        reviewFieldSaving,
        reviewMissingRequiredFields,
        reviewPriorityColor,
        reviewQueue,
        reviewQueueCounts,
        reviewQueueFilters,
        reviewReadyFieldsCount,
        reviewRequiredFieldComparisons,
        reviewRuleForm,
        reviewRuleSaving,
        reviewRuleTypes,
        reviewRules,
        reviewServiceAssigning,
        reviewServiceForm,
        reviewServiceName,
        reviewServiceSaving,
        reviewVehicleLinkingId,
        reviewVehicleSearch,
        reviewVehicleSearchLoading,
        reviewVehicleSearchResults,
        rootDocumentKindOptions,
        saveRepairLoading,
        selectCatalogScope,
        selectedDocumentId,
        selectedFile,
        selectedFleetVehicle,
        selectedFleetVehicleId,
        selectedFleetVehicleLoading,
        selectedManagedUser,
        selectedManagedUserId,
        selectedRepair,
        selectedRepairAwaitingOcr,
        selectedRepairComparisonAttentionCount,
        selectedRepairDocument,
        selectedRepairDocumentExtractedFields,
        selectedRepairDocumentFieldSnapshots,
        selectedRepairDocumentManualReviewReasons,
        selectedRepairDocumentOcrServiceName,
        selectedRepairDocumentParts,
        selectedRepairDocumentPayload,
        selectedRepairDocumentWorks,
        selectedRepairHasBlockingFindings,
        selectedRepairReportSections,
        selectedRepairUnresolvedChecks,
        selectedReviewCategory,
        selectedReviewItem,
        serviceCities,
        serviceCityFilter,
        serviceForm,
        serviceLoading,
        serviceQuery,
        serviceSaving,
        services,
        setActiveWorkspaceTab,
        setAdminResetPasswordValue,
        setAttachedDocumentFile,
        setAttachedDocumentKind,
        setAttachedDocumentNotes,
        setAuditActionTypeFilter,
        setAuditDateFrom,
        setAuditDateTo,
        setAuditEntityTypeFilter,
        setAuditSearchQuery,
        setAuditUserIdFilter,
        setBackupRestoreConfirmValue,
        setBatchReprocessLimit,
        setBatchReprocessPrimaryOnly,
        setBatchReprocessStatusFilter,
        setCheckComments,
        setDocumentComparison,
        setDocumentComparisonComment,
        setDocumentVehicleForm,
        setFleetQuery,
        setFleetStatusFilter,
        setFleetVehicleTypeFilter,
        setGlobalSearchQuery,
        setHistoricalImportFile,
        setHistoricalImportLimit,
        setHistoricalWorkReferenceMinSamples,
        setHistoricalWorkReferenceQuery,
        setHistoryFilter,
        setHistorySearch,
        setLaborNormCategory,
        setLaborNormFile,
        setLaborNormImportBrandFamily,
        setLaborNormImportCatalogName,
        setLaborNormQuery,
        setLaborNormScope,
        setLastUploadedDocument,
        setOcrLearningProfileScopeFilter,
        setOcrLearningStatusFilter,
        setOcrLearningTargetFieldFilter,
        setOcrProfileMatcherProfileFilter,
        setOcrRuleProfileFilter,
        setReviewActionComment,
        setReviewServiceForm,
        setReviewServiceName,
        setReviewVehicleSearch,
        setSelectedManagedUserId,
        setSelectedReviewCategory,
        setServiceCityFilter,
        setServiceQuery,
        setShowLaborNormCatalogEditor,
        setShowLaborNormEntryEditor,
        setShowLaborNormImport,
        setShowLaborNormListDialog,
        setShowOcrLearningListDialog,
        setShowRepairOverviewDetails,
        setShowReviewFieldEditor,
        setShowReviewRuleEditor,
        setShowReviewRuleListDialog,
        setShowReviewServiceEditor,
        setShowServiceEditor,
        setShowServiceListDialog,
        setShowUserEditor,
        setUserSearch,
        setUserVehicleSearch,
        showLaborNormCatalogEditor,
        showLaborNormEntryEditor,
        showLaborNormImport,
        showLaborNormListDialog,
        showOcrLearningListDialog,
        showRepairOverviewDetails,
        showReviewFieldEditor,
        showReviewRuleEditor,
        showReviewRuleListDialog,
        showReviewServiceEditor,
        showServiceEditor,
        showServiceListDialog,
        showUserEditor,
        statusColor,
        systemStatus,
        techAdminTabDescriptions,
        token,
        updateBrowserRoute,
        updateLaborNormCatalogFormField,
        updateLaborNormEntryFormField,
        updateOcrProfileMatcherFormField,
        updateOcrRuleFormField,
        updatePartDraft,
        updateRepairDraftField,
        updateReviewFieldDraft,
        updateReviewRuleFormField,
        updateServiceFormField,
        updateUploadFormField,
        updateUserAssignmentFormField,
        updateUserFormField,
        updateWorkDraft,
        uploadFileInputRef,
        uploadForm,
        uploadLoading,
        uploadMissingRequirements,
        userAssignmentForm,
        userAssignmentSaving,
        userForm,
        userLoading,
        userSaving,
        userSearch,
        userVehicleSearch,
        userVehicleSearchLoading,
        userVehicleSearchResults,
        usersList,
        usersTotal,
        vehicleExportLoading,
        vehicleSaving,
        vehicleStatusColor,
        vehicles,
        workspaceTabReturnLabels,
      })}
          />
  );
}
